packaging.gemspec
sub only replaces the first instance of a match, but for git describe,
we need to replace all instances of - to get a valid gem version. This
commit makes that change.
=> (maint) Use gsub instead of sub in gemspec

lib/packaging/config/params.rb, spec/lib/packaging/config_spec.rb, templates/msi.xml.erb
With the push for all in one agent packages, we're renaming our puppet
msi. This rename is so that the msi will be more in sync with the rest
of our puppet agent packages. This work is needed to build the windows
installer now that https://tickets.puppetlabs.com/browse/PUP-3844 has
been merged.
=> (RE-3710) Update the msi name

tasks/ship.rake
Prior to this commit, we kept running into issues where centain
variables we not being populated. This was because we never invoke the
`pl:fetch` task, which looks for and sets all remote variables defined
in the build-data repo. New updates to the gem ship task requires this
information, whereas before we didn't. The gem ship will fail unless we
add this task requirement.
=> (maint) Ensure we fetch necessary vars for gem ship

templates/msi.xml.erb
We need to be able to build an MSI for Puppet that includes cfacter.
This updates the xml template that creates the msi build job to include
the needed updates.
=> (PUP-3854) Update automation for cfacter

templates/msi.xml.erb
In the Puppet 3.x series, we ship two msi's, one with the `-x64` suffix,
and one without. In the Puppet 4.x series, this changes to include the
arch for both packages. Unfortunately, this convention wasn't maintained
in previous changes meant to support to move to including architecutre
in both builds. This commit adds back the naming convention for builds
in the 3.x series by only appending the architecture if the build is
64bit.
=> (maint) Maintain naming conventions

lib/packaging/deb/repo.rb
Previously, if there were no deb repos to sign, the nightly repo ship
would explode, because we try to call each on a possibly nil object.
This commit updates the method to helpfully let us know that there were
no deb repos to sign if dists is nil.
=> (maint) Update sign_repos for deb to handle failure

lib/packaging/deb/repo.rb, lib/packaging/rpm/repo.rb, spec/lib/packaging/deb/repo_spec.rb, spec/lib/packaging/rpm/repo_spec.rb
Previously, if rpms and debs hadn't both been built, various repo
related methods would explode in failure when trying to wget, retreive
or ship repo/repo configs. This breaks a lot of automation when
developing a new project when only one platform may be being built. This
commit rectifies this by warning and returning early from these methods
instead of failing completely.
=> (RE-4008) Make repo tasks more fail friendly

lib/packaging/deb/repo.rb, spec/lib/packaging/deb/repo_spec.rb
Previously if the directory did not exist, it could not be considered
empty. That is fine for the implementation of empty_dir?, but isn't good
for the ship_repo_configs method. This commit updates the bailout
section to also return early if the directory does not exist at all.
=> (RE-4008) Update conditional to also check for non-existence

lib/packaging/deb/repo.rb
In a previous commit, some additional whitespace was added to the deb
repo heredoc, which totally prevents reprepro from parsing it. This
commit removes that whitespace.
=> (RE-4008) Remove whitespace from deb repo heredoc

lib/packaging/config.rb, tasks/deb.rake, tasks/pe_ship.rake
This commit moves 'deb_build_targets' and 'rpm_build_targets' methods
to the Pkg::Config class to so they can be accessed from
enterprise-dist tasks.
=> (RE-3836) Move rpm and deb _build_targets methods to Pkg::Config

tasks/pe_ship.rake
Currently, the regex used to ship PE components breaks on the
CumulusLinux-2.2 codename due to an optimistic split('-')
This updates with a regex (the same one used before the above change
was implemented) that matches correctly.
=> (re-4028) Fix bad regex in pe_ship that breaks Cumulus

tasks/pe_sign.rake
This enables signing for sles-10 and sles-12 packages, aligning with sles-11 and EL.
=> (maint) Fix signing for sles 10 and 12 packages

lib/packaging/config/params.rb, lib/packaging/deb/repo.rb, spec/lib/packaging/config_spec.rb, tasks/deb.rake, tasks/mock.rake
Previously the packaging repo was limited to shipping to main/production
or devel, based on the versioning scheme of the project being shipped.
This commit extends that to allow the rpeo to be overriden for apt or
yum repos using a param in the yaml file. apt_repo_name and
yum_repo_name are both available to override the defaults.
=> (RE-4045) Add support for alternate repositories

lib/packaging/config/params.rb, lib/packaging/util.rb, lib/packaging/util/misc.rb, spec/lib/packaging/config_spec.rb, spec/lib/packaging/util/misc_spec.rb, tasks/jenkins.rake, tasks/ship.rake
If the user has used the new Pkg::Config.apt_repo_command or
Pkg::Config.yum_repo_command, we want to prefer those commands over the
legacy defaults. This PR adds logic to check if the new param is
set, and if so to invoke it, and otherwise to fall back to the old
behavior. The freight rake task is renamed to update_apt_repo, and the
uber_ship is updated to use it instead of freight.
=> (RE-4139) Update ship taks to use repo_command if set 

lib/packaging/config/params.rb, spec/lib/packaging/config_spec.rb, tasks/ship.rake, templates/packaging.xml.erb
For vanagon projects, tarballs will not be produced. This breaks the
uber_ship, which expects a tar to be there. This commit addresses this
by adding a build_tar parameter which defaults to true, which can be
used to toggle the tar ship/build. The TAR environment variable can also
be used to set this on the command line.
=> (RE-4261) Add build_tar config parameter

tasks/ship.rake, templates/packaging.xml.erb, templates/repo.xml.erb
With the shift to delivering our software via the puppet-agent package,
we want to discontinue shipping conventional packages. However, we do
want to continue shipping the tar and gem artifacts.
This commit lets us maintain a list of LTS build targets for community
members who are using this automation to build rpm or deb packages while
not building rpm/deb packages when we run `rake pl:jenkins:uber_build`.
It also lets us easily not ship any deb/rpm packages. The important this
is that `pl:deb` and `pl:mock` still work for building deb/rpm packages
if that is wanted. If the setting needs to be overridden, like for a
jenkins uber_build, we can do that by setting `RPM=TRUE` and/or
`DEB=TRUE` as environment variables when that rake task is invoked.
=> (RE-4221) Allow building and shipping of only tar/gem artifacts

templates/repo.xml.erb
Previously, the automation allowed empty strings to used in the `cows`
and `final_mocks` definition. In changes that I made recently, I took
away that functionality. This only impacts repo creating, which fails if
there are no packages of that kind to create a repo for.
This commit makes it so that we will not attempt to create repos in any
of the following situations:
`cows:`
`cows: ''`
`#cows: base-lucid-amd64.cow`
and will attempt to create repos only in the folowing situations:
`cows: base-lucid-amd64.cow`
=> (maint) Allow mock and cow list to be empty strings

tasks/sign.rake
A previous commit made building the tar optional, but neglected to make
signing the tar optional as well. This commit updates the sign_all task
to only sign the tarball if Pkg::Config.build_tar is true.
=> (maint) Only sign tar if the tar has been built

bin/uber_ship
This commit adds an uber_ship binary to packaging. This file serves two
purposes. First, it allows us to ship ezbake projects in a more
automated fashion than was previously possible. Running `./bin/uber_ship
puppetserver 2.0.0` would ship puppetserver 2.0.0 to our public repos,
without any of the manual steps that are currently required.
The second purpose is to reship a given package. For puppetdb, we will
be shipping the 2.3.x to two repos, products/main and PC1. This was not
possible with our previous tooling. With this commit, if a third
optional argument is included, the packages will be rearranged under the
target repo given, and shipped there. For puppetdb, that means that
2.3.3, which was targeted at main/products, can be rearranged under the
PC1 repo structure and shipped to our …
=> (RE-4292) Add uber_ship binary to packaging

lib/packaging/util/version.rb, spec/tasks/00_utils_spec.rb
Previously, ezbake builds would have a SNAPSHOT build that was treated
like any other. This had the consequence of making the 'final' release
for a given version series as less than the SNAPSHOT builds, which means
it would be unpromotable (also not immediately upgradable from the
snapshot version). This commit updates the versioning in packaging to
treat SNAPSHOT builds as if they were RC builds. This means that
SNAPSHOT versions will have a '0.1' prepended to them (0.7.0.SNAPSHOT...
becomes 0.7.0-0.1SNAPSHOT...), which makes the final version higher than
the snapshot version for packaging purposes.
=> (RE-3293) Treat SNAPSHOT builds like RCs for versioning

tasks/sign.rake
When building a vanagon noarch package, the x86_64 directory won't
always be created. When hardlinking, this will mean that there won't be
hardlinks of the noarch packages in the x86_64 directory. This commit
avoids that problem by ensuring that the x86_64 directory is created
before the hardlink is attempted.
=> (RE-4374) Create x86_64 dir during rpm signing

tasks/pe_ship.rake
In debugging failures, having more verbose output will be useful. This
commit adds the verbose flag to the repsimple calls to enable that.
=> (RE-4666) All repsimple calls should pass --verbose

tasks/pe_ship.rake
Previously the ship task would collect the output from repsimple and
scan it for errors, but it would not be printed to the screen. This
commit ensures that both stdout and stderr from the command are printed
to the screen for debugging purposes.
=> (RE-4666) Print output from repsimple call

tasks/pe_ship.rake
Previously the promotion would continue rolling even on errors creating
repos using reprepro. This commit addresses that by checking the output
of the repsimple call for errors and failing if any are found. This will
be coupled with a change to repsimple itself to exit non-zero on
reprepro errors.
=> (RE-4669) Fail promotion on reprepro errors

tasks/sign.rake
Currently in packaging you can't ship SLES or eos builds because you
can't sign them, because they were never run through the packaging repo
tasks before. With the advent of vanagon, this is now a requirement, so
here we go.
Sometime in the future, we should consolidate pe_sign.rake and sign.rake
into something that is smarter, but for now this should get us
unblocked.
=> (RE-4595) Allow RPMS for SLES and eos to be signed

tasks/sign.rake
When we added nxos and SLES support for rpm signing, AIX was missed.
This fixes that by adding AIX to the older_rpms signing patterns.
=> (RE-4595) Add AIX rpms to the list that packaging repo signs

templates/msi.xml.erb
Prior to this commit, our Windows packaging jobs required two key
commands:
- `#!C:/puppetwinbuilder/sys/ruby/bin/ruby.exe`
- `call c:\puppetwinbuilder\setup_env.bat`
The first of these commands hard-coded the Ruby runtime, and the second
used a hard-coded path to a file on each of the Windows builders that
set up certain parts of the environment (e.g. `%PATH%`) so the builds
could actually take place.
With the work I've been doing to manage our Windows build infrastructure
with Puppet, we can ensure that our tooling is always available on
`%PATH%` and is managed using the Chocolatey package manager, ensuring that
we don't need to bundle and distribute binaries or explicitly modify or
hard-code pieces of the environment.
This commit modifies the shebang that Jenkins uses to find a Ruby …
=> (maint) Fixes for Windows builder environment

tasks/nightly_repos.rake
For some builds it will be preferable to have autosigned builds shipped
to directories according to their version, and not their ref. This makes
them easier to identify based on an already installed package and will
enable internal ships of puppet-agent to proceed. This commit adds a
new parameter to the deploy_signed_repo task. If versioning is set to
ref, the current behavior is maintained. If it is set to version, then
the repo_configs are updated and the repos are shipped to a directory
named after the dotted version. The deploy_nightly_repos shim is also
updated here to pass ref to maintain current behavior.
This PR also includes a substantial refactoring of the tasks in the nightly_repos.rake file.
=> (RE-4681) Enable shipping of builds using version instead of ref

tasks/ship.rake
Prior to this commit, directories were being created on
builds.puppetlabs.lan with 755 permissions. This is fine except when
we need to add additional directories to them. For instance, when we do
a release, we create a 'shipped' directory under the main sha/tag
direcotry. This would cause ships to break because it would be unable to
create the 'shipped' directory. This commit updates the ship process to
always create directories with 775 permissions.
=> (RE-4155) Ensure directories are created with 775 perms

lib/packaging/util/net.rb, spec/lib/packaging/util/net_spec.rb, tasks/nightly_repos.rake
This PR includes some refactoring to the deployed repos tasks and also 
adds two new tasks to nightly_repos.rake. The first is a
task that ships an already signed repo to a given s3 bucket and the
second is a wrapper task that first signs repos for a given project and
SHA and then ships it to s3.
A new method is also added to Pkg::Util::Net to enable syncing out of repos to s3.
=> (RE-4684) Add automation to ship repos to s3

tasks/ship.rake
For shipping build tools, we need to ensure we can ship sles packages as
well as all the other rpm based packages. This commit also alphabetized
the list of rpm based platforms that we ship.
=> (maint) Add sles to the packages that we will ship

lib/packaging/deb/repo.rb, lib/packaging/rpm/repo.rb, lib/packaging/util.rb, lib/packaging/util/gpg.rb, spec/lib/packaging/util/gpg_spec.rb, tasks/00_utils.rake, tasks/nightly_repos.rake, tasks/pe_sign.rake, tasks/release.rake, tasks/sign.rake
Previously our rpm repos were unsigned. However, this breaks sles repo
usage that expects the repomd files to be signed. This commit begins
signing all repomd.xml files in a new sign_repos method, which is called
in the nightly_repos.rake tasks. Non-sles platforms happily ignore
signed repomd.xml files, so this is safe to apply everywhere.
This PR also includes moving the gpg and keychain methods into Pkg::Util::Gpg.
=> (RE-4880) Sign rpm repos during signed repo creation

tasks/mock.rake
This updates the dist macro. As explained in RE-4897:
> Previously we incorrectly specified the dist macro. All --defines passed
> along the command line are accessed using % in the spec file, but
> defined without it on the command line. This commit removes the % so
> that the dist macro can be correctly defined for platforms that don't
> already have it available (el4, el5, sles10).
=> (maint) Use correct dist macro definition in mock_defines

tasks/nightly_repos.rake
When version == ref, the repo_configs will be named the same and moving
them onto themself won't work, and will fail the job. This commit avoids
the entire rewrite conditional in the case that the ref is equal to the
version, as it is not needed then.
=> (RE-4907) Update nightly_repos to avoid ref == version problems

lib/packaging/osx.rb, tasks/nightly_repos.rake, tasks/sign.rake
This PR adds osx signing automation to the nightly repos task. To do that it adds a parameter to the sign method of Pkg::OSX.
=> (RE-4956) Add osx signing to nightly repos tasks

lib/packaging/deb/repo.rb
Previously we would only look for i386/amd64 architecture for packaging.
This commit adds all sorts of other arches. If we have no packages of
that arch, nothing fails.
=> (CPR-157) Allow packaging repo to build deb repos with more arches

lib/packaging/deb/repo.rb
Apparently all is some sort of meta-arch and doesn't need to specified,
and if you do specify it, things blow up. Who knew?
=> (maint) Remove all as an arch

tasks/tickets.rake
- Until automation is added around gems, manually smoke test them
=> (maint) Add instructions for smoke testing gems

tasks/tickets.rake
This commit adds two roles to the vars list (OWNER,TESTER). These
roles along with the others are added to the description of the
Go/No Go ticket to ensure that the stakeholders are explicit.
=> (RE-5224) Add stakeholders to Go/No Go ticket

.travis.yml
We no longer support Ruby 1.8 in the packaging repo. Previously, this
was kept around because we were using some builders that only had Ruby
1.8 available for use. However, we have since gotten rid of those
builders, and now have the luxury of having at least Ruby 1.9 in all
situations where we will use the automation in the packaging repo.
=> (maint) Remove Ruby 1.8

Gemfile
We no longer support Ruby 1.8 in the packaging repo. We can now remove
Ruby 1.8 specifics from the Gemfile
=> (maint) Remove Ruby 1.8 specifics from Gemfile

.travis.yml
Without `sudo: false` in .travis.yml, the tests will run on legacy
travis infrastructure; this means that tests take FOREVER to run.
Since we shouldn't need root access to test this repo, we can speed
up our runs by disabling root access. Eg. `sudo: false`.
=> (MAINT) Let Travis use modern infrastructure

tasks/tickets.rake
Prior to this commit, the ticket for Jira tidy up suggested that
the "introduced in" query be made against version "X.Y.Y" and the
"fixed in" query against "X.Y.Z". Since both should be made against
the same version (the version being released), this description
was a little misleading and has caused some confusion.
Update the rake task so that they are both for version "X.Y.Z".
=> (maint) Be more clear about version queries

tasks/sign.rake
We had this problem where, if a package was noarch, we assumed we were
building it for both i386 and x86_64 architectures. However, there are
some platforms that we only build one architecture for. In the case of
these platforms that we built 64-bit packages for, we're not actually
signing them. So, that's a problem. This commit flips the logic of the
problem. I've decided 64-bit packages are more important than 32-bit
packages.
=> (maint) Swap logic around which architecture to sign

tasks/sign.rake
Prior to this commit, the `pl:sign_swix` and
`pl:sign_all` tasks fail if there are no swix
packages to sign. Current enterprise-dist
package promotion workflow removes packages
that won't be promoted into enterprise-dist
before invoking packaging's `pl:sign_all`
task. This means swix packages are removed
before the signing attempt, which causes
package promotion to fail, since there are
no swix packages to sign.
This commit adjusts the `pl:sign_swix` task
so it does not fail if there are no swix packages
to sign. (This is similar to the current
behavior of `sign_svr4` and `sign_osx`.)
=> (RE-5613) Don't fail if no swix packages to sign

tasks/nightly_repos.rake
Previously the tar command used to pack up repos did not specify owner
or group, which meant that it was set to the user running the task,
which is generally jenkins. This user/group won't always exist on the
system that is fetching the tarballs, so this commit updates the tar
invocation to also pass --owner=0 --group=0 to ensure that it is set to
root or root's equivalent when packing.
=> (RE-5573) Update tar creation to set group and owner to root 

lib/packaging/config/platforms.rb
In the initial work I neglected to update the cumulus codename to be a
string and not a symbol in the platform hash. This breaks the whitelist
automation if cumulus is included.
=> (maint) Platform codenames can't be symbols

lib/packaging/osx.rb
Currently, when signing osx pkgs, when the automation
retrieves the DMGs it's dropping them in the PC1 directory,
meaning when we ship we ship signed packages in the wrong
location, and unsigned packages in the correct location.
This updates the retrieval to put the packages in the correct
location when they get retrieved.
=> (RE-5577) Fix osx signing paths

tasks/nightly_repos.rake
The task now takes a target host, the directory the puppet-agent source
is expected to be found in (minus the version/ref), the pe target to
link puppet agent into, and the same versioning param included in other
jobs (takes versioning/ref). The following rake task should link
puppet-agent into pe: `rake
pl:jenkins:link_signed_repos[agent-downloads.delivery.puppetlabs.net,/opt/puppet-agent,/opt/puppet-agent/${remote_prefix}/puppet-agent,version]`
=> (RE-5550) Update link_signed_repos task

tasks/nightly_repos.rake
We don't want to symlink latest into the PE version since lastest
deployed is not deployed for all PEs, and linking the version doesn't
have the correct repo_configs, so copy latest over to the version of PE
we're shipping for.
=> (RE-5550) Latest was not set correctly

tasks/jenkins.rake, tasks/ship.rake
Previously the uber_ship neglected to include update_ips_repo, which is
good because any builds that didn't have solaris 11 packages would have
failed in a large ball of flames. This commit adds update_ips_repo to
the uber_ship task and also updates the task itself to not fail but just
to helpfully warn so that builds without solaris 11 packages won't fail.
=> (maint) Let's actually ship ips packages during the uber_ship

tasks/ship.rake
This improves consistency with the other update_*_repo tasks that
already live under remote.
=> (maint) Move update_ips_repo to the remote namespace

tasks/ship.rake
Previously aix rpms couldn't be uber_shipped because they weren't
included in the ship_rpms search. This commit adds the aix directory to
the ship task, to ensure they will be shipped.
=> (maint) Also ship aix rpms in the uber_ship

tasks/nightly_repos.rake
Previously the checks were insufficient in the nightly repos ship job
for projects that have not defined foss_platforms to whitelist nightly
repo ships. If foss_platforms were nil, the empty? check would explode
in a empty? not defined for nilclass error. This is bad. This commit
avoids that problem by ensuring that foss_platforms is set and non-nil
before running .empty? on it.
=> (maint) Add nil check for foss_platforms in nightly_repos.rake

tasks/ship.rake
There were some old conditionals that made the update_ips_repo task only
exist for vanagon packages or when explicitly building for IPS. We fail
gracefully within the task if there are no solaris packages, so this is
unnecessary.
=> (maint) The task should always exist

tasks/sign.rake
This reverts commit 896ea5f035fb9a4dc76774d87d6692bdfdb1e874.
Currently, signing on AIX is broken, and it prevents us from signing any
other packages
Conflicts:
tasks/sign.rake
=> Revert " (RE-4595) Add AIX rpms to the list that packaging repo signs"

tasks/sign.rake
A previous commit removed aix packages from signing,
but now the task fails because they are still left in
the total package list after the signed packages
have been removed.
This removes the aix packages from the list so they
will be ignored for the signing check.
=> (RE-4595) Do not fail for unsigned aix packages

lib/packaging/util/execution.rb, lib/packaging/util/net.rb, spec/lib/packaging/util/net_spec.rb
It is currently fairly difficult to get details of why a command has
failed or what it returned by default in the packaging repo. This commit
aims to make that a little easier but adding a parameter to the ex
method to expose what command was executed and what it returned.
This PR also includes a commit which passes the verbose parameter to the ex method when rsync_to
and rsync_from methods are invoked. This should give a better picture of
what is happening when debugging failures.
=> (maint) Add debug flag to Pkg::Util::Execution.ex

lib/packaging/util/rake_utils.rb, tasks/puppet-agent-release-tickets.rake
This commit adds a new rake task, agent-release-tickets.rake, which
specifies a new set of instructions for releasing puppet-agent.
Steve and I are looking into using a set of known filters updated per-release instead of building them in the task itself. We'd need standard filters:
1) All tickets (across all components) in this release
2) 'Affected in and fixed in this release' public filters
3) All resolved tickets in this release (to be closed at the end).
Potentially, Steve could maintain these filters and have them ready to go before a release begins. That would make this task less error prone, as the user wouldn't need to know the versions of all of the components. The pre-existing filters would be all that's necessary. /cc @barlowst
=> (PUP-5446) Add new rake task for puppet-agent release ticket creation

lib/packaging/config/platforms.rb
Add OSX 10.11 to platform hash in preparation for shipping to nightlies.
=> (RE-5966) Add OSX 10.11 to platform hash

lib/packaging/config.rb, lib/packaging/config/params.rb, lib/packaging/deb/repo.rb, tasks/fetch.rake, tasks/ship.rake
`:apt_signing_server` is a new value that can be added to a project's `build_defaults.yaml` file or the [build_data](https://github.com/puppetlabs/build-data) repo. It allows a user to target a new Apt repo signing server, hopefully divorced of the public shipping infrastructure (since we used to just reuse the `:apt_host` value).
=> (RE-1198) Change how/where deb packages are signed and deployed

tasks/jenkins.rake, tasks/ship.rake
- Rename `pl:deploy_debs` to `remote:deploy_apt_repo`
- Add  `remote:deploy_apt_repo` to `pl:jenkins:uber_ship`
- Formatting cleanup for the Array of tasks that `pl:jenkins:uber_ship` runs
=> Some quick updates for the new Deb signing pipeline

lib/packaging/deb/repo.rb, tasks/ship.rake
We don't want to ship the entirety of the freight output since it creates an entire copy of the repository on each run. This updates the rsync command to only copy the actual changes.
Additionally this adds support to initially copy to a staging directory on the APT_HOST to avoid network quirks causing issues with the apt repository.
=> (RE-5998) Updates to debian shipping

tasks/agent-tickets.rake
New agent platforms need to be added to build_defaults so they can be
appropriately whitelisted for nightlies, and they need to be added to
the S3 and internal agent ship jobs so they can be used by PE.
=> (RE-5812) Add missing steps for new agent platforms

lib/packaging/config.rb, lib/packaging/config/params.rb, tasks/pe_ship.rake
For PE, we want to allow the promotion and use of arbitrary
test/dev packages into feature branches of PE, that don't pollute
the mainline PE branches and repos.
This adds logic to enable shipping to the feature repos for a PE branch,
and during a normal ship/promotion, links the shipped package into the
feature repos (so that mainline packages are immediately available to the
feature branches).
=> (RE-5619) Allow shipping to PE feature repos

tasks/jenkins.rake
We were running this manually after we accidentally broke the world a
bunch. The past several deployments have worked using this task run
manually, and I'm as confident as ever that this change will not break
anything. So this commit adds remote:deploy_apt_repo back to the
uber_ship.
=> (maint) re-add remote:deploy_apt_repo to the uber_ship

lib/packaging/deb/repo.rb
Manually mangling permissions is the worst. Except for maybe the sticky
bit. The sticky bit is definitely terrible. This stops rsync from
trying to set the group of things on apt.puppetlabs.com and removes the
sticky bit, because rsync does not listen to -s with its chmod.
=> (maint) Update permissions for the deb deployment

lib/packaging/deb/repo.rb
While this does nothing for the sticky bit, everything else fails
without this option. So, add it back so rsync will actually sync.
=> (maint) Re-add the Dugo-s to the chmod

tasks/agent-tickets.rake
Since the PA project exists we should always use that for platform
additions. We also always want puppet_agent_configuration to be part of
the PA project, and c_toolchain and build tools should be either in PA
or RE depending on whether or not the platform is PE only.
=> (RE-5813) Use PA as the parent project for agent platform tickets

tasks/agent-tickets.rake
When new platforms are being added, the platform hash in packaing should
be updated to include the new platform so it can be added to whitelists
and blacklists and the like.
=> (RE-5631) Update packaging platform hash

tasks/ship.rake, tasks/sign.rake
Platform has changed from RPM to DEB.
I'm not seeing any need to specify cumulus as a DEB platform, so this PR only removes huawei from the RPM tasks. Please let me know if I need to explicitly add huawei to the DEB tasks.
=> (maint) Remove HuaweiOS from RPM tasks

lib/packaging/config/platforms.rb
As part of ongoing processes to support Ubuntu 15.10 this commit
adds Ubuntu 15.10 to the platforms hash in order to facilitate
shipping 15.10
=> (RE-6150) Adding Ubuntu 15.10 to the platforms hash

tasks/tickets.rake
This commit adds the creation of a release ticket for updating
the PE versions that the puppet-agent pipelines should be
promoting to.
=> (PA-133) Add ticket for PE promotion updates

tasks/agent-tickets.rake
This updates the platform additions ticketing task to remove steps now unnecessary since moving pipelines to JJB and Beaker-HostGenerator. Since this is contains several very small updates to the same file it may be easiest to review the commits individually.
I'm unaware of a good way to test these changes, perhaps you can help @melissa ?
@kylog , @joshcooper , and @er0ck these are the changes we discussed in HC.
@jpartlow this includes the similar update for the Integration team that I mentioned.
/cc @waynr and @jameswagner2015 this updates the ticketing script for platform additions to the more self-service workflow we've discussed.
=> Update platform additions to JJB and BHG processes

tasks/apple.rake
Without this change, rake fails to execute successfully unless the
project has `build_dmg: TRUE`. Given that we do not build dmgs for most
of our projects, this is a problem. The issue originates at
https://github.com/puppetlabs/puppet/commit/307c653ac361682609b6226d861de61946c1df9e#diff-0704014ee01c1d6dd1028f281ec1dc4cR55
I have no idea why that was added in or what it does, but in order to
handle the change, this commit allows the 'package:apple' task to be
loaded, but effectively created an empty task unless the project has
`build_dmg: TRUE`.
=> (maint) Allow package:apple task to load regardless

lib/packaging/config/params.rb, lib/packaging/rpm/repo.rb, lib/packaging/util/net.rb, tasks/jenkins.rake, tasks/ship.rake
We used to ship our RPM repos directly to our perimeter nodes, which in the new world is sort of not getting the job done anymore. We should be shipping them to a staging server instead. This PR is tracking the work needed to move new RPMs from our local machine to our staging server, and then from our staging server to our production infrastructure.
=> (RE-6070) Ship RPMS to YUM_STAGING_SERVER

Gemfile
The jira ticket rake tasks depend on the jira-ruby gem, so this
adds a bundler gem group for jira functionality.
=> (maint) add a bundler group for jira tasks

Gemfile
This PR adds a constraint around ActiveRecord, depending on the Ruby revision (which should be safe as this is an integer which only goes up, and is sane; unlike `RUBY_VERSION`). This will let us use newer versions of `jira-ruby` without worrying about accidentally pulling in ActiveRecord 5 now that `jira-ruby` has unconstrained their ActiveRecord requirements.
While I was in there, I also updated the Ruby hash syntax (since a `Gemfile` is kinda just a big dumb Ruby hash) and mangled quotes so that they're consistent across the file.
=> Polish up the Gemfile

tasks/ship.rake
Some tasks requires yum_staging_server or apt_signing_server.  We need to fetch that data to be able to use it.
=> (RE-6286) Add pl:fetch to tasks to get build data

tasks/puppet-agent-release-tickets.rake
The ship packages task should include shipping the latest puppet-agent
release to S3 for the applicable branch of PE.
=> (maint) Ship puppet-agent to s3

tasks/jenkins.rake
Some projects such as pl-build-tools do not use a separate signing/staging server for repos.  As such we only need to update apt/yum repo locally.  This commit exludes the shipping jobs when the staging/ship host is the same.
=> (RE-6453) Exclude apt/yum shipping when on same host

lib/packaging/platforms.rb
Without requiring 'set', the #to_set method will not be available on Arrays.
=> (RE-6493) explicitly require 'set'

lib/packaging/deb/repo.rb, lib/packaging/rpm/repo.rb, lib/packaging/util/net.rb, tasks/ship.rake
We want to set group and ownership correctly on staging, then preserve these permissions when shipping.
This also addresses a few failures we were seeing.
=> (RE-6498) Fix permissions when shipping

tasks/pe_sign.rake
Inside the pe:sign rake task, there is
a branching statement checking for OS
family and version. the check against
version was a check of >= against a string
which likely caused problems. this commit
makes OS integer in to an integer instead.
See https://github.com/puppetlabs/packaging/blob/master/tasks/pe_sign.rake#L20-L24
for more details
=> (RE-5372) Fix signing bug

lib/packaging/config.rb, lib/packaging/util/rake_utils.rb, tasks/config.rake
I thought it would be, so in service of some of my other work I bashed two rocks together to make this. It'll add two rake tasks to make validating/viewing the current state of a project's config easier.
=> (MAINT) Wouldn't it be rad to view Pkg::Config in a readable format?

lib/packaging/util/file.rb
Namespacing is hard, and we use `File#directory?` and `File#exist?` all over Packaging. When I tried fixing them, I gave up around the 170th instance of `File#somethingorother` and instead made some passthrough methods in the existing `Pkg::Util::File` class.
This is a dirty hack, and it shouldn't be how we do business. But it'll unblock things while we rename the `Pkg::Util` classes that conflict with core or stdlib classes.
=> (MAINT) Fix broken calls to ::File class methods

lib/packaging/util/file.rb
This was left off of the last hotfix, and it causes Packaging
to explode in new and interesting ways.
=> (RE-6596) Fix missing argument to File.directory?

README.md, lib/packaging/deb/repo.rb, lib/packaging/gem.rb, lib/packaging/rpm/repo.rb, lib/packaging/tar.rb, lib/packaging/util.rb, lib/packaging/util/execution.rb, tasks/ips.rake, tasks/jenkins.rake, tasks/mock.rake, tasks/ship.rake, tasks/update.rake, tasks/version.rake, tasks/z_data_dump.rake
I've got a laundry list of nitpicks that are making shipping painful. Let's do some laundry.
What I'm aiming for is giving us the ability to selectively skip jobs when running `pl:jenkins:uber_ship` and breaking apart large tasks until they're functionally irreducible (while preserving existing interfaces as much as possible). My hope is that once we've reduced the quantity of work to irreducible tasks that we can then start recomposing the rollups (tasks like `pl:jenkins:uber_ship` or `pl:uber_ship`) into tools more resilient tasks with less churn around the process of getting software someplace our customers can see it.
=> Deferred maintenance for health and safety

tasks/puppet-agent-release-tickets.rake
Update the ticket generation to include the steps in
https://confluence.puppetlabs.com/display/RE/Puppet+Agent+Release+Branching
=> (RE-6575) Update ticket generation for release branch workflow

tasks/apple.rake
@apple_bindir and @apple_libdir are manually entered, but can be generated using data from file_mapping.yaml.
=> Use definitions from file_mapping.yaml where possible

lib/packaging/util/execution.rb
This hack totally breaks git tag parsing if you try to use DRYRUN.
It's being pulled out until Pkg::Util::Execution#ex can be refactored.
=> (MAINT) Remove short-sighted DRY-RUN hack

tasks/fetch.rake
Currently, when retrieving the build_data fails for
some reason, the error message is incomplete and
doesn't provide the necessary information to troubleshoot.
This adds some (hopefully) useful output.
=> (maint) Add useful output to fetch task

lib/packaging/deb/repo.rb, lib/packaging/platforms.rb
This enables the creation of powerpc deb repos, which we need now
that we're including huaweios builds for that platform.
=> (maint) add additional architectures available for deb repo generation

lib/packaging/ips.rb
For some reason pkgsign has started failing, again. Trying to clean up
the whitespace in the command in case that is actually the reason.
=> (maint) Try to cleanup whitespace for pkgsign

lib/packaging/ips.rb
We were doubly rsyncing p5p packages to rama. We should only be sending
them out once. Also, trying to create two repos in the same path in
immediate succession may be causing weird caching errors in the repo
management commands needed for signing. Since we're cleaning up the
workspace anyways after each run let's set it up in a new directory too.
=> (maint) Improvements to IPS workflow

lib/packaging/util/jira.rb, lib/packaging/util/rake_utils.rb, tasks/platform-removal.rake
Added a rake task to facilitate the removal of supported platforms.
Usage:
```
PE_ONLY=true SERVER=true PLATFORM_TAG=remove_x86 JIRA_USER=user JIRA_INSTANCE=https://jira.host rake pl:platform_removal
```
PE_ONLY is for platforms that are only contained in PE
SERVER is for platforms that are also puppetserver / puppetdb hosts
=> (RE-5816) Add a task for platform removal tickets

tasks/platform-removal.rake
Adds two more subtasks to track deprecating pe_repo platform classes,
and to file a future ticket to remove them completely in the next PE
major.  This came up as a result of our forgetting to deal with pe_repo
during the removal of Debian6, Ubuntu 15.04 and 15.10, and the dance
around upgrades and installations which may have these platform classes
already declared.
=> (maint) Add subtasks for pe_repo during platform removal

lib/packaging/config/params.rb, spec/lib/packaging/config_spec.rb
When executing `package:gem`, copy the `gem_required_ruby_version` and
`gem_required_rubygems_version` from the project_data.yaml to the
Gem::Specification so that the resulting gem can be constrained on
unsupported ruby/rubygem versions.
=> (RE-7052) Allow setting required ruby and rubygems versions

lib/packaging/util/jira.rb, tasks/tickets.rake
Previously tickets were created in the default open status, which means
that a human needs to update them to be ready for engineering so that
they appear on agile boards. This commit updates the tickets to be
created in the "Ready for Engineering" state to avoid this manual step.
=> (maint) Create tickets in "Ready for Engineering"

lib/packaging/rpm/repo.rb
We don't want all the options --archive brings in, we actually only want
--recursive and --links. --archive was causing issues with timestamps on
symlinks. Manually syncing with --recursive and --links instead of
--archive allowed the rsync to run successfully.
=> (maint) RPM rsyncs failed while shipping today

tasks/ship.rake
Windows was shipping to /opt/downloads/windows/windows instead of
/opt/downloads windows due to a missing trailing slash in the source
path.
=> (maint) Missing trailing slash in rsync command

tasks/platform-removal.rake
The copy pasta in the pl:platform_removal task had conflicting anonymous methods.  There was also a race condition introducted in an prior commit.
=> (CPR-342) fix pl:agent_tickets and pl:platform_removal tasks

tasks/gem.rake
Commit 72751690 added the ability to set gem_required_ruby_version (and
rubygems), but I forgot to git add the change to the gem task to copy
the build params to the generated gem specification.
=> (RE-7052) Copy build params into the specification

lib/packaging/config/params.rb, lib/packaging/gem.rb, tasks/ship.rake
We need to be able to ship gems to both nexus and stickler. This commit
splits out the internal_gem_host to allow us to either default to the
original value or to assign each separately.
=> (maint) Add the ability to push gems to both destinations

lib/packaging/util.rb, lib/packaging/util/file.rb, lib/packaging/util/git_tags.rb, lib/packaging/util/misc.rb, lib/packaging/util/rake_utils.rb, lib/packaging/util/version.rb, spec/fixtures/configs/components/test_file.json, spec/fixtures/configs/components/test_file_not_tagged.json, spec/lib/packaging/util/file_spec.rb, spec/lib/packaging/util/git_tag_spec.rb, spec/lib/packaging/util/version_spec.rb, tasks/vanagon.rake
This adds a component tagging check for packaging. This (for now) is only a
human check and not a barrier for any CI jobs or builds using
pl:jenkins:uber_build. This commit adds the vanagon:check_tags and
vanagon:build_all rake tasks. The latter of which should replace the human
invocation of pl:jenkins:uber_build when we ship vanagon projects. The new
vanagon:build_all task is really just a wrapper for uber_build that adds
check_tags and a prompt.
Basically this is a human checklist, meant to notify the user if something
"looks tagged". It will not prevent shipment or builds, it will simply output
what "looks tagged" and then ask if this looks correct.
=> (RE-6989) Add component tag check

tasks/puppet-agent-release-tickets.rake
We now have a vanagon:build_all rake task that humans should use when shipping
puppet-agent. the task is a wrapper around pl:jenkins:uber_build that adds a
tag check beforehand. update the ticket automation to reference this task.
=> (maint) update P-A ticket automation to mention vanagon:build_all

tasks/ship.rake
Move the checking for whether or not to ship the tar within the rake
task rather than outside of it.
=> (maint) Always define the tar task

tasks/puppet-agent-release-tickets.rake
Due to the "decoupling" of component releases from the Puppet-Agent release, we
no longer need to smoke test gems or components during the P-A shipment. This
smoke testing step should happen as part of the component releases instead.
=> (maint) update P-A ticket automation to remove smoke test step

tasks/agent-tickets.rake
I keep forgetting to ensure facter is compiled for new platforms with
java. This isn't an issue until we try to add a server package for the
new platform, and everything fails because the server package can't
utilize the facter available via puppet-agent. Rather than try to
remember this, let's just be explicit and get facter.jar for all
platforms.
=> (maint) Add ticket to compile facter with java

tasks/jenkins.rake
Currently in uber_ship we run tasks to update and deploy repos every time.
We only want to run these if the packages actually exist.
=> (CPR-368) Only run uber_ship tasks when packages exist

tasks/education.rake
This commit adds a rake task that takes a vm and corresponding md5 file and ships them to the specified host.
=> (RE-7259) Add task to deploy training VM.

tasks/nightly_repos.rake
Prior to this commit, the s3/internal puppet-agent ship called this rake
task to generate signed repos to ship out. This task called automation
to sign both packages and repos prior to bundling them up and shipping
them out. We thought for some reason that the sign_all task was used to
sign the packages. This was an incorrect assumption. In order to sign
the MSI packages, we need to explicitly invoke the msi sign method on
the packages. This commit adds that logic to ensure we are actually
signing our packages.
Hopefully I'm not missing anything this time.
=> (RE-7411) Sign MSIs prior to s3/agent ship

tasks/jenkins.rake
Previous version did not recursively check all subdirectories for packages. Fixed this issue so multiple levels of subdirectories can be searched.
=> (RE-7428) Bug fix of check to see if packages exist before deploying

tasks/nightly_repos.rake
This commit adds a 'verbose" to one of the lines in order to debug the issue with the recursive symlink
=> (RE-6147) Internal Puppet Agent Shipping Creates Recursive Symlink

lib/packaging/ips.rb
I've had enough of failing ENV vars. This is going to hard code the locations
of the solaris signing certs as an interim fix. We will need to entirely
refactor where we set these environment vars anyway, so for now at least things
won't fail anymore.
=> (maint) update solaris signing with hardcoded values

tasks/ship.rake
When we deploy tar, msi, swix, and dmg files from staging to production,
they end up with a newer timestamp on production than they do on staging
since we don't preserve timestamps (and preserving timestamps causes
permissions headaches so we shouldn't do that). For the other deploy
tasks we add the --update rsync flag so that we ignore files that are
newer in production than in staging. This commit adds that flag to the
tasks that ship tar, msi, swix, and dmg files.
=> (RE-7406) Timestamps erroneously updated for tar, msi, swix, and dmg

tasks/education.rake
This commit updates the symlinking so that the vbox and vmware files are linked to the student ova when the training VM's are shipped.
=> (RE-7584) Create complete set of student training VM links

tasks/pe_ship.rake
This replaces our use of reprepro and repsimple in the shipping of pe
repos with aptly.
=> (RE-7445) Migrate pe repos to use aptly

tasks/ship.rake
The logic uses inline string construction alot, this PR updates all that string
construction to instead use variables.
=> (maint) update windows symlink logic to use correct version

tasks/ship.rake
Since the source MSI lives in the same directory as the link target, the
source should just be the file name not a more qualified file path.
=> (maint) Windows symlinks were not getting created correctly

README.md
The exiting key is expiring soon, so update the readme to use the new
one.
=> (maint) Update to use a new key

tasks/education.rake
This commit adds in logic to check to see if the symlink to be
replaced is broken. If it is, then it removes the symlink so it can
create a new one. This will help reduce manual intervention when the
symlinks get all strange, because computers.
=> (maint) Update linking to be smarter

lib/packaging/platforms.rb
In preparation for buliding OS X 10.12 "Sierra" agents.
=> (RE-7841) Add osx 10.12 (Sierra) platform

tasks/education.rake
Previously, this could would attempt to unlink if the link didn't even
exist or if it was truly a broken symlink. This commit updates the check
to be sure there is actually a link that points to a non-existent file.
This means if we're creating a brand new set of links, then our
automation won't bomb out on us.
=> (maint) Unlink only if it's actually a broken link

lib/packaging/deb/repo.rb, spec/lib/packaging/deb/repo_spec.rb
This commit changes how we create one-off repos for development use.
Prior to this, we had been using reprepro to create and then later to
sign repos. These repos contain development builds on
builds.delivery.puppetlabs.net, nightlies.puppetlabs.com,
agent-downloads.delivery.puppetlabs.net, and s3.
Some of the repos, such as those on s3, do contain final builds made
available to our enterprise customers.
This commit switches out reprepro for aptly. Aptly handles repos
slightly differently, which adds a little complexity to this work. We
have to explicitly create the repo, add packages to it, and publish the
repo. In order to maintain the same directory structure that was
generated with reprepro, we must then link the dists and pool
directories into our working directory. This is done with …
=> (maint) Move reprepro repo creation to aptly

lib/packaging/deb/repo.rb, spec/lib/packaging/deb/repo_spec.rb
Previously the check to see if we were using reprepro or aptly was in
the wrong place. This was failing in such a way that all repos were
reprepro based. This commit fixes that mistake.
=> (maint) Update aptly check

lib/packaging/deb/repo.rb, spec/lib/packaging/deb/repo_spec.rb
We need to access the aptly files via wget. However, wget doesn't
retrieve hidden files. This commit removes that quality of the aptly
config file and directory
=> (maint) Ensure aptly directories not hidden

lib/packaging/osx.rb, lib/packaging/util/net.rb, spec/lib/packaging/util/net_spec.rb
This fixes a couple of issues with the remote_ssh_command method to prevent it from echoing output when we don't want it, and to actually return output when we want it to.
This also updates the OSX signing command to correctly exit on errors instead of proceeding and potentially silently failing while returning unsigned packages.
=> (PA-552) OSX signing should not echo the command output

tasks/pe_ship.rake
We recently ran into an issue where one or the other of these values
return nil, which broke the automation. This should fix it.
=> (maint) Don't fail if nil

lib/packaging/config/params.rb, lib/packaging/util.rb, tasks/jenkins.rake, tasks/retrieve.rake, tasks/ship.rake
This PR includes a number of stability improvements and safety checks to make it more reliable to run pl:jenkins:uber_ship with FOSS_ONLY=true.
Still todo:
=> (RE-8179) Add the ability to ubership quietly

lib/packaging/util.rb, tasks/config.rake
This modifies config:print to call pl:fetch first so that you see the actual variables that will be loaded during the ship, and also adds a config:print_hosts to allow you to check where things will be shipping.
=> (maint) cleanup config printing

tasks/retrieve.rake
With part of the FOSS_ONLY rework I did recently I added arch into the
filtering so we don't accidentally fetch arches we don't want to be
shipping. OSX packages don't contain the arch though, so we were no
longer getting any DMGs with FOSS_ONLY=true.
=> (maint) OSX packages don't have arch in the name

lib/packaging/util/misc.rb, lib/packaging/util/net.rb, spec/lib/packaging/util/net_spec.rb, tasks/ship.rake
This commit adds pl:ship_check to verify that shipping should work
before we actually try to ship. This will check things such as ssh
access to the necessary boxes, gpg keys available everywhere they are
needed, the needed gems are installed, and ownership is correct on the
gems on rubygems.
=> (RE-5982) Add ship check task

lib/packaging/osx.rb
Using the -v flag for `security unlock-keychain` echoes the command that
will be run, which interpolates the environment variable and prints the
passphrase passed on the command line. By switching that to -q (quiet)
the output is no longer printed.
=> (PA-552) Do not echo osx signing passphrase

acceptance/.gitignore, acceptance/Gemfile, acceptance/README.md, acceptance/Rakefile, acceptance/pre_suite/public.rb, acceptance/tests/install_smoke_test.rb
This commit adds the acceptance testing structure to the packaging repo, and adds a test for public build servers. This test simply installs puppet-agent from those locations, and does a smoke test to verify that the tools are callable once installed.
=> (RE-8190) add first acceptance test

tasks/retrieve.rake
With the addition of FOSS_ONLY we started doing a lot of wget filtering.
This means that we end up with empty directories during shipping that
will then get rsynced out to our public download infrastructure. We
shouldn't do that. This loops through the directories and removes them
recursively.
=> (RE-8359) Clean up empty directories in retrieve

lib/packaging/util/net.rb, spec/lib/packaging/util/net_spec.rb
This adds `set -e` to the remote ssh command by default.
=> (RE-8187) Default to failing if anything in the remote_ssh_cmd fails

lib/packaging/util/net.rb, spec/lib/packaging/util/net_spec.rb
Reverts puppetlabs/packaging#611
Appears to be causing problems in multiple pipelines. Reverting while we investigate
=> Revert "(RE-8187) Default to failing if anything in the remote_ssh_cmd fails"

tasks/vendor_gems.rake
We were calling the internal `fetch` method inside Bundler::Fetcher. Upstream
has started calling this an internal method, and moved it around, so now we
should be using the public version of this functionality.
=> (RE-8415) Fix Bundler's `fetch` not found error

lib/packaging/util/net.rb, spec/lib/packaging/util/net_spec.rb
This adds `set -e` to `remote_ssh_cmd` and also fixes the two cases I found where we were depending on a failure in a command passed to `remote_ssh_cmd`
=> (RE-8187) fail more!

lib/packaging/util/net.rb, spec/lib/packaging/util/net_spec.rb
Reverts puppetlabs/packaging#615
Found some more issues, in particular puppet-agent/vanagon promotions that have platforms in the build_data.yaml that don't exist in PE
=> Revert "(RE-8187) fail more!"

lib/packaging/deb/repo.rb, lib/packaging/gem.rb, lib/packaging/nuget.rb, lib/packaging/rpm/repo.rb, lib/packaging/util/execution.rb, lib/packaging/util/file.rb, lib/packaging/util/git.rb, lib/packaging/util/git_tags.rb, lib/packaging/util/gpg.rb, lib/packaging/util/jenkins.rb, lib/packaging/util/net.rb, lib/packaging/util/serialization.rb, lib/packaging/util/version.rb, spec/lib/packaging/deb/repo_spec.rb, spec/lib/packaging/rpm/repo_spec.rb, spec/lib/packaging/util/execution_spec.rb, spec/lib/packaging/util/file_spec.rb, spec/lib/packaging/util/git_spec.rb, spec/lib/packaging/util/git_tag_spec.rb, spec/lib/packaging/util/gpg_spec.rb, spec/lib/packaging/util/jenkins_spec.rb, spec/lib/packaging/util/net_spec.rb, spec/lib/packaging/util/version_spec.rb, tasks/apple.rake, tasks/deb.rake, tasks/jenkins.rake, tasks/jenkins_dynamic.rake, tasks/nightly_repos.rake, tasks/retrieve.rake
This is a reimplementation from #604. Rather than modifying the existing `ex()` method, I'm adding a new capture3 method so as not to interfere and change behavior with code using this method in enterprise-dist. I also converted all instances of `ex()` in the packaging repo to use `capture3`.
=> (RE-8186) Improved error handling in packaging

tasks/nightly_repos.rake
This adds a set of tasks to make a tarball of *all* of the
prepared repos, in addition to the individual per-platform tarballs.
This is useful for cutomers who have a PE master with
no internet access. They can unpack the puppet-agent-all tarball into the location that
pe_repo expects and use simplified agent install without needing internet access, or having to
manually download each agent that they need to feed to pe_repo.
=> (PE-16465) Make a tarball of all signed repos

lib/packaging/util/net.rb, lib/packaging/util/version.rb, spec/lib/packaging/util/net_spec.rb
After the initial work for this was merged in, failures became apparent
with razor packaging. Razor builds using JRuby 1.7.19. Whereas with ruby
2.1.8, we see
```
irb(main):004:0> Open3.capture3("echo 'hi' >/dev/null")
=> ["", "", #<Process::Status: pid 95032 exit 0>]
```
with JRuby 1.7.9 the same command results in
```
irb(main):005:0> Open3.capture3("echo 'hi' >/dev/null")
=> ["hi >/dev/null\n", "", #<Process::Status: pid=95178,exited(0)>]
```
This commit updates unnecessary piping in the code that checks
versioning and updates the method for curling to discard stdout when
curling quietly rather than dealing with pipes.
There are still pipes elsewhere in the code but this removes them from
enough places to allow razor to build successfully, and as that is the
only project that builds …
=> (RE-8186) Using pipes in Open3.capture3 with JRuby is special

templates/packaging.xml.erb
We're having a bunch of packaging timeouts on the deb builders possibly
due to hardware oversubscription. There is more hardware planned for
these boxes, but in the interim let's increase the timeout so fewer
things fail.
=> (maint) Double the timeouts, double the fun

lib/packaging.rb, lib/packaging/config/params.rb, lib/packaging/repo.rb, spec/lib/packaging/repo_spec.rb, tasks/nightly_repos.rake
Our automation is going to need to handle more that one set of platforms to
promote to PE. Instead of adding seperate jobs for seperate pipelines (i.e.
one for master, one for stable etc.) and continuing to carry around static
lists on top of information we already have, this commit adds the ability to
use the platform information in build_defaults.yaml to identify what platforms
promote.
This is done through a new pack_all_signed_repos_indivudually task, to replace
the pack_signed_repo task (that created the need for the list in the jenkins
job).
to faciliate this, the platform_repos data has been added to the available
data loaded in build_defaults.yaml, this data is in the following form:
platform_repos:
- name: platform-version-arch
repo_location: repos/platform/repo/location
=> (RE-6628) Add new pack_signed_repo tasks

tasks/nightly_repos.rake
The 'generate_signed_repos' task did not previously execute out of the pkg
directory. This meant that in a later step, when 'prepare_signed_repos'
attempted to clean work that was no longer required, there was nothing to
clean.
This PR remedies that, so the job's disk footprint can be drastically
decreased.
=> (QENG-4740) Call in to pkg directory in internal ship jobs

lib/packaging/repo.rb, spec/lib/packaging/repo_spec.rb
This commit handles the case where a platform in `platform_repos` does not have a `repo_location` specified. These platforms are now skipped when looping through to create all repo archives.
=> (RE-8615) Skip platforms without repos when creating repo archives

lib/packaging/deb/repo.rb
This is needed for the IBM Power8 platform.
=> (maint) Add ppc64el to the list of packaging architectures

tasks/mock.rake
This commit changes the rpm repo path to have the repo name come before the platform, rather than between the version and arch. It maintains the old repo path for PC1 though.
=> (RE-8702) For puppet5, change the repo path to something more sensible

lib/packaging/config.rb, lib/packaging/platforms.rb, tasks/ship.rake
This PR adds a `platform_data` hash that maps each platform to where its
artifact and repo_config (if applicable) can be found. This info will get added
to the <ref>.yaml file that gets generated when a package is built, allowing
beaker to consume this info without having to figure out the mapping itself.
=> (RE-8707) Add `platform_data`

README.md, lib/packaging/config.rb, lib/packaging/config/params.rb, spec/lib/packaging/config_spec.rb, tasks/retrieve.rake, tasks/ship.rake, tasks/sign.rake
This commit adjusts the loading of default configs to move on if project_data.yaml isn't found. Load will only fail if both project_data.yaml and build_defaults.yaml cannot be found.
=> (RE-8843) Don't fail if ext/project_data.yaml doesn't exist

lib/packaging/config.rb, tasks/ship.rake
This commit adds a `platform_data` hash that maps each platform to where its artifact and repo_config (if applicable) can be found. This info will get added to the <ref>.yaml file that gets generated when a package is built, allowing beaker to consume this info without having to figure out the mapping itself.
=> (RE-8707) Add `platform_data` to <ref>.yaml

lib/packaging/platforms.rb
This is the final thing needed so I can ship these packages to our build-tools repo.
=> (BUILD-69) Enable ppc64le package builds for el-7

tasks/mock.rake
We should only assume we're using the new layout if you've set the
yum_repo_name to something other than PC1. Otherwise you're probably
depending on the old defaults for something.
=> (maint) Don't change defaults if yum_repo_name isn't set

lib/packaging/util/git.rb, spec/lib/packaging/util/git_spec.rb
To determine ref-type we use `git cat-file -t`. If this is given a
describe that isn't a sha or a tag it will fail. So, add the ability to
have `describe` run just `git describe` instead of `git describe --tags
--dirty` (the default) so we can use that method for determining the ref
type.
=> (RE-8864) When determining the ref type we need a clean describe

lib/packaging/util/execution.rb
Right now that method just includes a generic failure message if the
called method fails the specified version of things. This just adds the
exception and the backtrace so you can actually debug what went wrong.
=> (maint) Print errors if you fail out of retry_on_fail

tasks/jenkins.rake
The repo updates can take a substantial amount of time. Doing all of
those before we start deploying them will reduce the amount of time in a
partially deployed state and make it easier to time the cache
invalidation.
=> (maint) Reorder the ubership to do all the updates before the deploys

tasks/jenkins.rake, tasks/ship.rake
Add three additional rake tasks to ship all repositories to S3 in addition to their current deployment targets.
This isn't quite ready to merge - it needs input from people more familiar with this process and code base.
For context, the sync script (`/usr/local/bin/s3_repo_sync.sh`) these commands invoke is deployed to weth using puppet, and handles both S3 upload and CDN cache clearing.
For the `:deploy_downloads_to_s3` task, I'm not sure which `Pkg::Config` setting to use. Right now I'm referencing `Pkg::Config.apt_signing_server` - which I assume is weth. Is that assumption correct? Is there a better config setting I can use? Create a new one?
I'm also not sure how to test this without risking accidentally shipping for real.
=> (RE-8842) Ship apt, rpm, and downloads to S3

tasks/ship.rake
Exclude *.html from the s3 sync, and add --delete to ensure we don't leave old stuff on the rsync servers after removing it from the repositories.
This is specifically intended to avoid syncing the generated HTML directory indexes to rsync, since it would be a behavior change for users of the rsync service.
=> Do not sync html files to rsync servers

lib/packaging/config/params.rb, lib/packaging/paths.rb, lib/packaging/util/version.rb, spec/lib/packaging/util/version_spec.rb
When testing automation changes or fixing last-minute packaging errors,
it can be desirable to check out a tagged version of a project and
modify build_defaults to use an alternate branch of packaging. This
allows you to pass the ALLOW_DIRTY_TREE environment variable to return
cause final? to return true if you're on a tagged build with a dirty
tree.
=> (maint) Add override to make tagged but dirty trees final

lib/packaging/config/params.rb, tasks/jenkins.rake
I bundled a few fixups for uber_ship into this PR as I was looking into needed changes for s3 shipping.
* Not all projects will ship to s3, so add the s3_ship parameter to ship to s3 when needed
* If we're shipping to s3 we don't need to do any of the deployment steps since we'll go right from staging -> s3
* The s3 shipping automates CDN invalidations, so we can remove the CDN warning
* There was a typo for swix tasks.
=> (maint) uber_ship fixups

lib/packaging/util/net.rb, tasks/ship.rake
This commit adds a function for finding the latest version of something and creating a 'latest' symlink to it. We do this for puppet-agent (and its components) for mac and windows. We now do this whenever we ship a dmg or msi.
=> (RE-8943) Update shipping automation to deal with 'latest' symlinks

lib/packaging/platforms.rb
This commit removes the f prefixed to fedora package version numbers.
=> (CPR-407) Enable shipping fedora packages to repos not prepended with f

tasks/ship.rake
The ask_yes_or_no messages were using `staging_host` but the actual
command was running on `apt_signing_host`. While these are the same
right now, this is dangerous, so we should be consistent.
=> (maint) Update host for the s3 download sync

lib/packaging/paths.rb, lib/packaging/platforms.rb, spec/lib/packaging/paths_spec.rb
Our initial regexes for determining platform were pretty open ended.
This lead to issues for instance with packages that matched 'el' (such
as puppet-release. woops), and could have easily been encountered with
codenames. This makes the regexes more anchored and adds some more test
cases.
=> (RE-8978) Make regexes more specific

tasks/education.rake
If we're shipping a new master or training VM, archive the existing ones
so we only have the latest VM at the top level.
=> (RE-8942) Update training VM shipping to archive old VMs

tasks/ship.rake
Exclude *.html from rsyncing to the rsync download servers.
Without this change, after we switch DNS users will download a ton of HTML files they don't care about.
=> Do not ship HTML directory indexes to rsync server

lib/packaging/config.rb, lib/packaging/platforms.rb
This PR updates the `platform_data` hash that beaker will consume. I have changed the artifact and repo_config paths to be relative to the location of the <ref>.yaml file (i.e. the artifacts directory) and removed the f prefix from the fedora keys (in this hash only). 
I also added back the non-f-prefixed versions to the `PLATFORM_INFO` map. This will allow us to locate paths with and without f prefixes. The breakage in the puppet-agent pipeline last week was due to packages on builds not having the f-prefix, but beaker looking for packages *with* the f prefix. I believe this was due to the removal of the f prefix in the puppet-agent vanagon configs, rather than anything packaging-related.
=> (maint) Updates requested by beaker team

tasks/fetch.rake
Setting `--depth 1` when cloning the build-data repo doesn't serve us
well. It prevents us from checking out the different branches we need to
check out. We need to be able to check out both the team specific and
project specific branch in order to load any extra data from them. We
can't do that with a shallow clone. This fixes that issue.
=> (maint) Do not shallow clone git repo

CHANGELOG.md
This commit adds in a changelog so we can start tracking what is in
specific releases of the packaging gem over time.
=> (maint) Prepare changelog for 0.6.0 release

lib/packaging/util/ship.rb, tasks/ship.rake
This commit adds and modifies existing automation around maintaining the
rolling repo links. We need to provide them for rpm, deb, eos, mac, and
windows repos.
=> (RE-8984) Create automation to update rolling repo

tasks/nightly_repos.rake
Because it is useful to have a file which has the latest version of a
released package on s3 for cgi-bin scripts to correctly resolve 'latest'
this commit creates automation around this task.
=> (RE-9133) Add task to packaging for syncing latest file to s3

lib/packaging/paths.rb, lib/packaging/platforms.rb, spec/lib/packaging/paths_spec.rb, spec/lib/packaging/platforms_spec.rb, tasks/sign.rake
This commit updates the packaging repo to handle source packages
correctly. Previously, sources would just be dropped into the first
supported architecture for whatever platform-version we're dealing with.
This will let us send them to the proper directories when we ship.
This also adds a new method to allow us to get the package format
without needing to worry about architecture.
=> (RE-8980) Drop sources into the correct directory

tasks/nightly_repos.rake
This commit allows packages to be released by passing in a version to
the update_release_versions task instead of having packaging get this
package from the repo it is in. This needs to be done because tagging is
inconsistent across the various projects we have and our automation
should be able to pass versions down through jenkins jobs.
=> (RE-9133) Require a version be passed to release a package

lib/packaging/config.rb
AIX artifacts have 'ppc' as the arch, so we encountered issues when mapping artifact paths to platform tags.
=> (maint) Change AIX arches from 'power' to 'ppc'

tasks/deb.rake
With no particular environment / setup, creating .deb packages in a puppetlabs project with…
```
rake package:bootstrap
rake package:deb
```
…fails with `TypeError: no implicit conversion of nil into String`.
This is due to the `codename` variable being *nil* (because `cow` is *nil*), which `File#join` does not accept as a valid argument.
Rely on `#to_s` so that this value is promoted to a valid `''` when *nil*.
=> (maint) Fix package:deb target

spec/lib/packaging/paths_spec.rb
AIX artifacts have 'ppc' as the arch, so we encountered issues when mapping artifact paths to platform tags. This adds AIX test cases to ensure we can figure out the platform tags correctly.
=> (maint) Add test cases for AIX artifact paths

tasks/retrieve.rake
This commit re-implements FOSS_ONLY when retrieving packages. It uses the artifact paths gathered in the <ref>.yaml file and only grabs artifacts for platforms listed as foss platforms.
=> (RE-8866) Fix FOSS_ONLY

lib/packaging/config.rb
Prior to this commit, we had been reporting unversioned msis in the
platform_data hash. This was fine for testing, as the unversioned msi is
simply a link to the versioned one. But this is bad when we go to ship
the packages. If we are fetching packages with FOSS_ONLY=true, it will
query the yaml data looking for foss only platform targets and fetch the
corresponding artifact. This is bad, since it means that for windows, we
were fetching the unversioned artifact for the final ship. This
changes ensures we don't set the unversioned msi when we are initially
writing out the platform_data hash.
=> (maint) Do not report unversioned msis

lib/packaging/config.rb, spec/lib/packaging/config_spec.rb
This PR addresses several issues in gathering artifact paths. When multiple artifact paths matched a given platform tag, only the last one would be saved to <ref>.yaml. We now have additional checks to make sure we're not grabbing debug packages, source packages, unversioned msis, etc.
=> (RE-9467) Fix how platform_data handles multiple entries for a given platform_tag

lib/packaging/artifactory.rb
Previously, the fact that we had been requiring the artifactory gem at
the top of this file meant that calling any rake tasks would fail if the
artifactory gem was not installed. This commit moves the requires inside
the init for artifactory, so that we only require that library when we
are actually using it.
=> (maint) Only require artifactory gem if we are using artifactory

lib/packaging/util/ship.rb, tasks/jenkins.rake, tasks/ship.rake
This PR adds automation for shipping nightlies the same way we ship final builds.
See individual commit messages for more details.
=> (RE-9525) Simultaneously ship nightlies to weth and old nightlies server

tasks/nightly_repos.rake
This commit removes the project name from the final synced path as it
when the S3 sync happens we get an extra directory too deep when syncing
files.
=> (maint) Remove project config from synced path

lib/packaging/deb/repo.rb, lib/packaging/repo.rb, lib/packaging/rpm/repo.rb
Care needs to be taken when combining && and || in a long command to
avoid running into operator precedence issues.
=> (maint) Using && and || can cause issues

lib/packaging/rpm/repo.rb, spec/lib/packaging/rpm/repo_spec.rb, tasks/nightly_repos.rake, tasks/rpm_repos.rake
In
https://github.com/puppetlabs/packaging/pull/693/commits/d036eba3666198b7e6f792a44aee60bcbc984f5c
the functionality for create_repos was modified from something that runs
repo creation locally to something that runs repo creation on a remote
host. To restore backwards compatibility we added create_local_repos and
create_remote_repos. The original create_repos method has been
deprecated in favor of create_local_repos and
create_repos_from_artifacts has been deprecated in favor of
create_remote_repos.
=> (maint) Restore backwards compatibility for create_repos

tasks/jenkins.rake, tasks/sign.rake
With this change, a jenkins job (or anyone else with a primed gpg-agent on a signing server) should be able to autosign RPMs without having to enter the passphrase.
=> Remote sign rpms

tasks/ship.rake
This commit adds a rake task for syncing nightlies to s3, the same way we sync apt, yum, and downloads.
=> (RE-9522) Add s3 repo sync task for nightlies

lib/packaging/rpm/repo.rb, spec/lib/packaging/rpm/repo_spec.rb
This reverts commit e2db10e343382df5a5695f42d18917f6c254aa41.
Since repo_creation_command is generating a command to be used later we
don't care if createrepo is available where we're generating the
command, but rather on the system it's run on.
=> Revert "(maint) Go back to using `Pkg::Util::Tool.check_tool`"

lib/packaging/util/ship.rb, spec/lib/packaging/util/ship_spec.rb
This commit sets directory ownership and permissions, in addition to package ownership and permissions, when a package is shipped.
=> (RE-9829) Automate permission setting

lib/packaging/util/net.rb
This commit adds checks for whether a file is directory when attempting to set ownership or permissions. Since we check for immutability by piping `lsattr` to `grep`, directories that contain immutable files were being read as immutable themselves. This fixes that by ignoring the `lsattr` result for directories.
=> (RE-9874) remote_set_permissions doesn't work on directories

lib/packaging/config.rb, spec/lib/packaging/config_spec.rb
This commit replaces 'power' with 'ppc' when listing AIX repo_config paths in platform_data, since 'ppc' is the arch used in package names.
=> (maint) Substitute 'power' for 'ppc' in AIX repo_config

lib/packaging/paths.rb, tasks/nightly_repos.rake
This commit adds an optional parameter `repo_target` to Pkg::Paths.repo_path. Previously, the value of Pkg::Paths.repo_name was used instead. This allows the nightly ship task to find builds using the (final) repo name, rather than the nonfinal repo name, when shipping to ravi. Ideally, this should be reverted once the old nightlies process is obsoleted.
=> (RE-9889) Nightly repo ship only generates repo configs, ships no artifacts

lib/packaging/paths.rb
This commit switches repo_path to use `options` as a parameter instead of a named parameter, since Ruby < 2.0 does not support named parameters.
=> (maint) Remove named parameters

lib/packaging/config.rb, lib/packaging/rpm/repo.rb, spec/lib/packaging/config_spec.rb
This commit excludes aix rpms when generating repo configs.
=> (RE-9948) generate_repo_configs tag creates repo config for aix

Gemfile, lib/packaging/config.rb, lib/packaging/util/rake_utils.rb, packaging.gemspec
This makes the needed changes to enable packaging to ship as a gem. In
my testing this also works for projects that are still using packaging
as a github repo, so it will allow projects to start moving to a gem
over time.
=> (maint) Prepare for shipping packaging as a gem

lib/packaging/platforms.rb, spec/lib/packaging/platforms_spec.rb
When compiling the list of valid architectures to validate a platform
tag, it doesn't include source architectures. This means that things
like `el-7-SRPMS` and `ubuntu-14.04-source` are not recognized as valid
platform tags.
=> (maint) packaging doesn't recognize source platform tags

lib/packaging/util/net.rb, tasks/nightly_repos.rake, tasks/sign.rake
This commit adds bundler usage to the `remote_bootstrap` command so that projects using the packaging gem can still use packaging tasks on a remote host
=> (RE-10225) packaging gem broke nightlies

lib/packaging/util/net.rb, tasks/nightly_repos.rake, tasks/sign.rake
This commit adds `.bundle/gems` as the path to install gems when executing remote rake tasks. Previously, `bundle install` could fail because the user did not have write permission to the default path.
=> (maint) Specify path for remote bundle installs

lib/packaging/retrieve.rb, spec/lib/packaging/retrieve_spec.rb
This PR adds `'level' => 1` as an option to `foss_only_retrieve` to ensure that all top-level artifacts (including source tarballs) are retrieved before platform-specific artifacts.
=> (RE-10238) FOSS_ONLY doesn't retrieve tarballs

lib/packaging/util/net.rb, tasks/nightly_repos.rake, tasks/sign.rake
This commit adds a check for Gemfile to the rake tasks that are executed
remotely. Previously, these commands would attempt a `bundle install` and then
fail if no Gemfile was found. Since not all projects are ready to use packaging
as a gem, we need to support the old method of using packaging (bootstrapping).
=> (RE-10247) Clojure project signing bundles don't have Gemfiles

lib/packaging/config.rb, lib/packaging/config/params.rb
This adds a new config variable for PE release branches,
and updates the ship tasks to ship to the correct locations
depending on release branch (vs feature or mainline)
=> Initial support for PE release branches

lib/packaging/repo.rb, spec/lib/packaging/repo_spec.rb, tasks/jenkins.rake, tasks/ship.rake
This PR modifies how we update apt and yum repos to be intentional about whether we are updating final or nonfinal repos, instead of relying on version magic.
See individual commit messages for details.
=> (maint) Separate nightly repo updates

lib/packaging/repo.rb, spec/lib/packaging/repo_spec.rb, tasks/ship.rake
This PR updates the update_repo methods to not fail if nil arguments are not required by the repo command.
=> (maint) Only fail repo updates if *required* params are missing

tasks/sign.rake
This commit changes how we link noarch packages after signing to only link to the arch where the package came from in the first place.
=> (RE-10318) Stop shipping noarch packages to unsupported arches

tasks/ship.rake
This commit adds separate rake tasks for updating ALL (final or nonfinal) yum
repos. Previously, the existing update_yum_repo and its nightly counterpart
would update all repos, but changes to the yum_repo_command change this
behavior. Usually we will only want to update the repo we're shipping to, but
this maintains ths ability to update all repos, should we want to.
=> (RE-9325) update_yum_repo updates ALL repos, not just ones we're shipping to

lib/packaging/platforms.rb, lib/packaging/util/ship.rb, spec/lib/packaging/platforms_spec.rb, tasks/ship.rake
This PR adds wrapper functions that use `ship_pkgs` and various link creation functions to ship different types of packages (rpms, debs, msis, etc.) and uses those in the various rake tasks for shipping.
This will be useful for [RE-10284](https://tickets.puppetlabs.com/browse/RE-10284).
=> (maint) Add and use separate functions for shipping different package types

lib/packaging/util/ship.rb, tasks/jenkins.rake, tasks/ship.rake
This commit adds separate rake tasks for shipping nightly packages. Previously,
we had single rake tasks for each package type that would switch between
shipping to the final repos and the nightly repos, based on the version of the
packages. This allows us to be intentional about what we're shipping where.
Note: I didn't add nightly tasks for svr4 and p5p since they are PE-only platforms right now.
=> (RE-10284) Separate final and nightly ship tasks

lib/packaging/ips.rb
Update to our new thawte code signing cert, good until March 2020.
The current cert expires later this month, so we shoudl start signing with the new one.
=> (RE-9870) Update Solaris 11 signing certs

lib/packaging/ips.rb
Our new code signing cert was signed with a different set
of intermediate and root CA certs, so we need to update those on
the solaris signer as well.
=> (RE-9870) Update intermediate and root CA certs

tasks/retrieve.rake
This commit adds a failure to the retrieve task if the local target (usually 'pkg') is empty at the end of the retrieve. Previously, the retrieve would appear successful, but future tasks would have nothing to operate on.
=> (maint) Fail retrieval if destination directory is empty

tasks/sign.rake
This PR updates signing tasks to not look for particular versions of the packages that need signing. See individual commit messages for details.
=> (RE-9425) uber_ship automation does not work for untagged ezbake builds

tasks/apple.rake
When building on macOS 10.13, hdiutil creates APFS images by default.
This is unnecessary and can cause issues on older releases, so specify
HFS+ instead.
=> (CPR-521) Create HFS+ images

lib/packaging/retrieve.rb, spec/lib/packaging/retrieve_spec.rb, tasks/retrieve.rake
The issue was a missing trailing slash..
=>  Revert "Revert "(maint) Remove `remote_target` param from `retrieve_all`""

lib/packaging/sign/deb.rb, lib/packaging/sign/rpm.rb
This commit changes the local signing functions to use `capture3` rather than `%x` so that failures are captured and reported.
=> (RE-10396) Fail explicitly when signing fails

lib/packaging/platforms.rb
This adds support for upcoming releases of the following platforms:
* Debian 10 'Buster'
* Ubuntu 18.04 'Bionic'
* Fedora 28
=> (maint) Add upcoming Debian/Ubuntu/Fedora platforms

lib/packaging/platforms.rb
This commit reorganizes the PLATFORM_INFO hash to look like the one in the 1.0.x branch. The info should all be the same (or additive), but this will make future merge-ups less painful.
=> (maint) Reorganize platform info

CHANGELOG.md, lib/packaging/platforms.rb, spec/lib/packaging/platforms_spec.rb
I'm hoping this PLATFORM_INFO reorg will be the last one we need to ensure smooth merge-ups in the future.
CHANGELOG conflicts resolved by adding info from master CHANGELOG to 1.0.x one.
lib/packaging/platforms.rb conflicts resolved by realigning everything to look like master.
=> Merge master -> 1.0.x

lib/packaging/paths.rb, lib/packaging/util/ship.rb, spec/lib/packaging/paths_spec.rb, tasks/nightly_repos.rake, tasks/ship.rake
Since the nightly ship tasks have been separated from the final ship
tasks, we can pass a variable through when we're working on a nightly
ship so we don't need to rely on the magic checking of whether or not
this is a final version.
=> (RE-10428) Paths were wrong for nightlies

lib/packaging/config.rb, lib/packaging/platforms.rb
This commit updates the `parse_platform_tag` function to return 'ppc' as the
architecture for AIX platforms. Officially, 'power' is the AIX arch, but we use
'ppc' in paths and file names, to be consistent with upstream expectations.
=> (maint) Use 'ppc' in AIX artifact paths

tasks/nightly_repos.rake
This commit fixes a copy paste error where we were shipping the
directory with the LATEST file in it instead of just the LATEST file
itself to the pdk repo.
=> (maint) Sync latest filename instead of the directory

lib/packaging/platforms.rb, spec/lib/packaging/util/platform_spec.rb
Having dashes in platform names causes problems when it comes to adding
a platform to pe_repo, so the redhat-fips platform name is being changed
to redhatfips.
=> (PA-1958) Rename redhat-fips platform to redhatfips

tasks/sign.rake
This change modifies the packaging ship rake task to work with signing before shipping to builds. It takes a repo_dir that a user wants it to sign, copies the files into mozart, transfers them into the /pkg dir (this part i'm not 100% on because testing is hard in mozart... ideally it would just sign in whatever dir you give it but in case there is not an updated version of packaging pulled in it will be looking to sign files that are in the pkg/ dir so that's what i have it doing for now) signs them, and sends them back to your local pkg/. This commit relates to https://github.com/puppetlabs/vanagon/pull/549 where you can see packages that have gotten signed. Working on getting more tests for different package types.
=> (RE-10422) Make separate signing step before shipping to builds

lib/packaging/util/gpg.rb
Currently the tarball signature will fail if the external
signature file already exists. This adds logic
to skip the tarball signing if it's already signed.
=> (maint) Skip tarball signing if signature already exists

tasks/pe_ship.rake
This commit ensures that if we're promoting to a PE release branch, we don't
link packages to the PEZ feature repos. Previously, if a package was promoted to
mainline and then to a release branch, PEZ would get whichever package was
added most recently, causing checksum mismatches.
=> (RE-10681) Don't link release branch packages to feature repos

lib/packaging/config/params.rb, lib/packaging/gem.rb, lib/packaging/nuget.rb, tasks/ship.rake
As we're migrating to Artifactory, we're deprecating nexus and stickler. This removes those configs and stops shipping to those services.
=> Updates to remove stickler and nexus configs

lib/packaging/retrieve.rb
FOSS_ONLY automation was previously relying on the artifact path in
<sha>.yaml to determine which artifacts to fetch. Rather than grabbing a
single artifact, grab all artifacts from the parent directory so we can
do things like ship termini packages.
=> (CPR-566) Grab all artifacts for a given platform/architecture

lib/packaging/config/params.rb, tasks/retrieve.rake, tasks/ship.rake
This commit adds a `PROJECT` environment variable that overrides/sets
`Pkg::Config.project` and adds explicit failures when shipping or retrieving
if the project is unset. Since we now have some repos that build multiple
different packages, we need to allow for different project names so that these
packages end up in separate directories on builds.
=> (RE-10703) Add `PROJECT` environment variable

lib/packaging/config/params.rb
`PROJECT` is in use in many places and with the nature of that change,
things are ending up in the incorrect repos on our builds server.
Updating that environment variable to `PROJECT_OVERRIDE` will allow us
to maintain the feature as needed while being less disruptive to
existing workflows.
=> (maint) Rename the `PROJECT` environment variable to `PROJECT_OVERRIDE`

lib/packaging/sign/rpm.rb, spec/lib/packaging/sign_spec.rb, tasks/sign.rake
This commit adds a check to the `sign_rpms` task to skip signing if the rpm is already signed. Previously, if we tried to sign more than once, a non-zero exit code would be returned, which caused failures.
=> (RE-10926) Check for signature before signing rpms

tasks/retrieve.rake
we previously weren't correctly grabbing the packages that we needed resulting in gems not getting shipped. with this update component packages will be appropriately fetched.
Tested with Puppet 5.5.2
=> (maint) update foss components to retrieve gems correctly

tasks/gem.rake
This makes more sense. It is also important for PA-2016 where we want
to simplify our component artifact + shipping job to not rely on jenkins:uber_build,
b/c jenkins:uber_build dynamically generates several jobs to do the work
that makes it difficult to diagnose failures.
Our simplified job will just run all of the possible packaging tasks in
sequence. If the specific packaging task does not apply to the given
component, the task will noop and pass-thru. We ship all of the
generated artifacts at the end.
=> (PA-2016) Have package:gem noop if the project does not build a gem

tasks/retrieve.rake, tasks/ship.rake
We updated the `PROJECT` environment variable to `PROJECT_OVERRIDE` but forgot
to update error messages.
=> (maint) Fix fail messages when 'project' is unset

lib/packaging/config/params.rb, lib/packaging/gem.rb, tasks/ship.rake
Resolved the conflicts by getting rid of the code that was being removed in 1.0.x, cherry-pick of f27f731555751cd7cf7d1a4339618899fc9be595
=> (maint) Remove stickler and nexus configs for gem shipping

lib/packaging/util/tool.rb
Windows executables can have spaces in the path, so surround the path found by
find_tool with "s on windows
=> (maint) Fix find_tool for windows

templates/packaging.xml.erb, templates/repo.xml.erb
This commit updates the templates used to generate the jenkins jobs for
building gems and tarballs (e.g. for razor-client, puppet, etc.) to `bundle
install` in order to use packaging as a gem.
=> (RE-10177) Update packaging and repo templates to bundle install

lib/packaging/util/net.rb, tasks/nightly_repos.rake, tasks/sign.rake, templates/packaging.xml.erb, templates/repo.xml.erb
This reverts commit f91132f15fb0205492c431e1c7ef98971f799270.
Forgot to handle the case of when `PACKAGING_LOCATION` is unset.
=> Revert "(maint) Export PACKAGING_LOCATION before doing remote bundle installs"

lib/packaging/util/net.rb, tasks/nightly_repos.rake, tasks/sign.rake, templates/packaging.xml.erb, templates/repo.xml.erb
Previously, even when PACKAGING_LOCATION is set locally, remote tasks (like
signing) were still pulling in the default version of packaging. Now, we pass
along this environment variable as part of our remote commands. Note that this
will not work if PACKAGING_LOCATION is set to a local directory. Instead, use
a git branch.
=> (maint) Export PACKAGING_LOCATION before doing remote bundle installs (take two)

lib/packaging/sign/rpm.rb, spec/lib/packaging/sign_spec.rb, tasks/sign.rake
This PR includes:
- Reverting the revert of the work I did on this previously, which includes:
- moving the rpm `sign_all` functionality out of the rake file and into the Pkg::Sign::Rpm module
- adding a `has_sig?` check to the `sign_all` method, so we skip signing already-signed things
- Refactoring `has_sig?`, including tests (see commit message for details)
=> (RE-10924) Package signing fails if already signed

tasks/sign.rake
This commit updates the `sign_all` task to rsync the signed packages back to
the `root_dir` that the packages were originally in, before signing.
Previously, we rsync'd back to `DEFAULT_DIRECTORY`, which may or may not be the
same as `root_dir`. This was an issue when signing vanagon projects: builds are
staged in a directory called 'output' and then shipped (internally) from there;
the `DEFAULT_DIRECTORY` is 'pkg', so when we attemped to sign between building
and shipping (internally), signed packages were getting rsync'd to 'pkg' but
the unsigned packages in 'output' were getting shipped.
=> (maint) rsync back to root_dir after signing

lib/packaging/platforms.rb, spec/lib/packaging/platforms_spec.rb
Added support for Ubuntu 18.10 cosmic cuttlefish.
I need this change in order be able to build pl-build-tools-release package.
=> Added platform support for Ubuntu 18.10 Cosmic

lib/packaging/sign/dmg.rb
This commit adds a conditional to the dmg signing method to skip signing if the
unpacked pkg file is already signed. As we work to move signing up in our build
process, we want to ensure that artifacts are signed only once so that all
copies of the artifact have the same checksum.
=> (RE-11600) Skip signing OSX pkgs if they're already signed

lib/packaging/sign/msi.rb
This commit adds a conditional to the msi signing method to skip signing if the
msi is already signed. As we work to move signing up in our build process, we
want to ensure that artifacts are signed only once so that all copies of the
artifact have the same checksum.
=> (RE-11600) Skip signing msis if they're already signed

tasks/sign.rake
This commit updates the `sign_deb_changes` task to loop through the .changes
files and sign them individually instead of passing a glob to the sign method.
Previously, this task was probably never getting called, since our shipping
workflow doesn't retrieve .changes files. Now that we have moved signing to
build time, we encountered an issue where the glob was not being interpretted /
expanded properly. This aims to fix that issue.
=> (maint) Sign deb changes files individually

lib/packaging/paths.rb
This commit updates the `link_name` method to take an optional `nonfinal`
param rather than pivoting on the build version. Much of our existing
automation already does this. Without this change, when final builds get
shipped to nightlies (which sometimes happens due to how teams have their CI
configured), a link gets created from the `repo_link_target` to the
`nonfinal_repo_name` (e.g. puppet -> puppet6-nightly). Instead, we want
`nonfinal_repo_link_target` -> `nonfinal_repo_name`.
=> (RE-11714) Be explicit about final vs nonfinal link name

lib/packaging/paths.rb, spec/lib/packaging/paths_spec.rb
This commit adds a `release_package_link_path` method that takes a platform tag
and constructs the the target path for the top-level release package symlink
associated with that platform, taking into account whether this is a final or
nonfinal (i.e. nightly) release package.
Currently, updating these symlinks is a manual process. This is the first step
in an effort to automate these updates.
=> (maint) Add method for determining release package link paths

packaging.gemspec
This commit pins the artifactory gem to ~> 2. Version 3.0.0 was just released
and it requires ruby >= 2.3. Since we still support older versions of ruby, we
must continue using a pre-3.0 version of artifactory.
=> (maint) Pin artifactory gem to ~> 2

lib/packaging/platforms.rb, spec/lib/packaging/platforms_spec.rb
I've added RHEL 8 to the platforms list, but I need someones confirmation that I've added it to the correct place. It's a bit confusing that there is only one entry for RHEL, (and that is 'redhatfips'). 
The current version is a common x86_64 arch, how come redhatfips is separate from the others?
=> (PA-2326) Addded RHEL8 to platforms.rb

CHANGELOG.md, lib/packaging/util/net.rb
This commit escapes the '\d' and adds quotes around the <package_name>-\<version>
regex we use for finding the latest version of a project and symlinking to it.
Previously, without the escape or quotes, we ended up searching for the literal
string '-d' after the package name (e.g. 'puppet-bolt-d'), which resulted in no
new -latest symlinks when we shipped a new version.
=> (RE-11984) Use quotes when grepping a regex

.travis.yml, tasks/ship.rake
Vanagon now generates build_metadata.\<project>\.\<platform\>.json for each
<project> and <platform> rather than overwriting 'build_metadata.json'
Make packaging copy all the files it finds (via glob) rather than the single
static file.
This seems like a simple change. However, I've not yet tested it -- trying to figure out how to test packaging changes has been elusive to me. The purpose of the PR at the moment is to see if it makes sense to people more familiar.
=> RE-12062 Copy all the build_metadata*.json files

.travis.yml
I updated the Travis ruby versions but neglected to update the exclusions.
This fixes that.
=> (maint) return old functionality excluding rubocop from older ruby versions

CHANGELOG.md, lib/packaging/config.rb
With the change to track all artifacts in the yaml metadata, the
location for repo configs for legacy (puppet-agent 1.10.x) fedora repos
was inadvertantly changed. This restores the original behavior.
=> (maint) Fix legacy fedora repo config issue

lib/packaging/util/ship.rb
This commit updates the calls to the `remote_create_latest_symlink` method to
take into account whether we are shipping nightlies or not. Previously, the
path we tried to link from for nightlies included a final repo name (e.g.
puppet6 instead of puppet6-nightly), so those paths weren't found in the
nightly repositories and links were not created.
=> (CPR-677) Create 'latest' symlinks for nightly msis and dmgs

lib/packaging/archive.rb
This commit updates the commands to recursively adjust ownership and
permissions on the apt archive directories to start earlier in the path.
Previously, we encountered `Permission denied` errors as we attempted to move
packages to directories that weren't included in the permissions adjustment.
=> (maint) Adjust permissions earlier in the archive path

lib/packaging/platforms.rb
Updated the `PLATFORM_INFO` hash at https://github.com/puppetlabs/packaging/blob/master/lib/packaging/platforms.rb to include Fedora 30 (amd64).
=> (PA-2678) Update puppetlabs/packaging platform hash to include Fedora 30 (amd64)

tasks/ship.rake
This commit removes the `--delete` flag from the `deploy_to_rsync_server`
process. As we plan to archive EOL packages, we want people using our rsync
servers to be able continue to do so with minimal effort on our part, so,
rather than maintaining a separate rsync server for archives, we'll just keep
packages available on the existing ones FOREVER.
=> (maint) Don't delete packages from rsync servers

CHANGELOG.md, lib/packaging/artifactory.rb
We recently found anonymous deletions were enabled on the repo we were
targeting. When we removed that permission, the error message for
promoting a package that already exists changed. As a result of this, we
also found we were using an invalid field in our error messages.
=>  (maint) Update regex for error when repromoting a package

lib/packaging/sign/msi.rb
We need to be able to loop through timestamp servers, and if the first
signing fails `set -e` will cause the code to exit. Instead, after each
signature if it was unable to sign successfully, explicitly `exit 1`.
=> (maint) Don't use `set -e` for windows signing

lib/packaging/util/net.rb, spec/lib/packaging/util/net_spec.rb, tasks/pe_ship.rake
These are intended as debugging. Not sure whether we'll want to keep them
after the bug has been indentified.
* Turn off --quiet in createrepo
* Let remote_ssh_cmd take a 'trace' flag
* Turn on the remote_ssh_cmd trace flag in the :update_remote_repo task
* Update some of the specs to deal with multiple shell 'set' commands
=> (RE-12463) Try to find the source of the SIGTERMs in packaging.

tasks/ship.rake
tldr: allow skipping the `ship_gem_to_downloads` task if `gem_host` is unset so that projects can keep using `uber_ship_lite` (which includes `ship_gem`, which includes `ship_gem_to_downloads`), but fail if `gem_path` is unset so that we don't accidentally ship to a weird path.
see individual commit messages for details
=> (RE-12520) Don't try to ship gems with unset params

lib/packaging/artifactory.rb
Tested by shipping pe tarballs to artifactory and then deleting them. Will be called in enterprise-dist during compose if not all platform cells succeed in the compose job because we don't want partial ships
=> (RE-12499) Add function to purge tarballs from artifactory if a compose fails

spec/fixtures/config/ext/build_defaults.yaml, spec/fixtures/config/ext/project_data.yaml, spec/fixtures/config/params.yaml, spec/lib/packaging/config_spec.rb
Be nice to Windows users (and generally a good citizen overall) by replacing
symlinks in the spec directory with actual files.
See the Jira for testing notes for this change.
=> (RE-11765) remove symlinks in the gem

lib/packaging/artifactory.rb
There are sometimes md5sum mismatch errors when shipping to artifactory, so let's calculate the md5sum of the file we want to ship to artifactory and include it when shipping to ensure accuracy. I'm hoping this will resolve the md5sum mismatch errors we've been seeing when trying to compose (mismatch md5s between packages.json and what lives in artifactory).
=> (maint) Calculate + ship md5sum of package

tasks/ship.rake
Because these files when built are exclusively named after the version of the package
there will be multiple files with that name (ex. 2019.2.0.yaml) so we can't treat these files like other built packages where we do not ship if a package of that name already exists on artifactory
Tested with a set of packages that already existed on artifactory, yaml was shipped but others were not
=> (maint) Always ship .yaml and .json files

lib/packaging/repo.rb, spec/lib/packaging/repo_spec.rb, tasks/nightly_repos.rake
Refactor repo.rb a bit so that 'create_all_repo_archives' also
creates a tarball of all the repos. Remove some old duplicating
code.
I've been testing with this Jenkins job: https://jenkins-master-prod-1.delivery.puppetlabs.net/job/experimental_exg_all_repos_test/
The resulting tarballs are being uploaded to Artifactory: https://artifactory.delivery.puppetlabs.net/artifactory/scratchpad__local/experimental_exg_all_repos_test
=> (PE-16465) Implement "all" tarball of repos

lib/packaging/artifactory.rb
Tested with LATEST file on artifactory
Because the artifactory gem only supports searching with artifact_name + repo but not a specific path, grab any files that match the name/repo (which we'd expect multiple LATEST files in the generic_enterprise__local repo) but then check their download uris for the provided path and only download the one that matches.
=> (RE-12729) read LATEST file

lib/packaging/artifactory.rb
when we release PE we make a release branch and copy over pe components
to release repos. 
next step will be to write something up to clear these out after a release, should be a lot easier now with erics pattern searching work. enterprise-dist PR https://github.com/puppetlabs/enterprise-dist/pull/3559
tested with a fake release branch and it populated `release/` https://artifactory.delivery.puppetlabs.net/artifactory/rpm_enterprise__local/2018.1/release/
=> (RE-12767) Populate release repos

lib/packaging/artifactory.rb
This commit renames the method to copy PE artifacts from one subdirectory to
another to be more generic, since there's nothing specific to release repos in
this method.
=> (maint) Make Artifactory PE repo population more generic

lib/packaging/artifactory.rb
this is a generalized function that can be used to delete all the artifacts with any specified repo + pattern but we'll use it for clearing out release artifacts from release/ 
tested [here](https://artifactory.delivery.puppetlabs.net/artifactory/rpm_enterprise__local/2018.1/release/el-6-x86_64/) by deleting some artifacts
previously I had also written a pretty ugly method that copies release artifacts back from release/ to repos/ but after thinking about it I realize that this isn't necessary because all packages specified in the base branch's packages.json will already have been promoted to repos/ and this would just be copying over packages that either already exist there or are out of date.
enterprise-dist pr to come
=> (RE-12771) clean out release repos after PE release

lib/packaging/artifactory.rb
Tested with 2018.1.0-rc10, was able to download the tarballs
=> (RE-12732) Add ability to download pe beta tarballs to local directory

lib/packaging/artifactory.rb
This commit replaces the `update_latest_file` method with a more generic
`upload_file` method. There was nothing in the `update_latest_file` method that
was actually specific to updating the LATEST file, so this generic method can
be used in its place. This allows for more reusability.
=> (maint) Add generic method for uploading a file to Artifactory

lib/packaging/artifactory.rb
Tested with puppet-agent package:
`Removing reverted package https://artifactory.delivery.puppetlabs.net/artifactory/rpm_enterprise__local/2018.1/repos/el-6-x86_64/puppet-agent-5.5.16.161.g4fa9432-1.el6.x86_64.rpm
Removing reverted package https://artifactory.delivery.puppetlabs.net/artifactory/rpm_enterprise__local/2018.1/repos/el-7-x86_64/puppet-agent-5.5.16.161.g4fa9432-1.el7.x86_64.rpm
Removing reverted package https://artifactory.delivery.puppetlabs.net/artifactory/rpm_enterprise__local/2018.1/repos/sles-12-x86_64/puppet-agent-5.5.16.161.g4fa9432-1.sles12.x86_64.rpm
Removing reverted package https://artifactory.delivery.puppetlabs.net/artifactory/debian_enterprise__local/2018.1/repos/ubuntu-16.04-amd64/puppet-agent_5.5.16.161.g4fa9432-1xenial_amd64.deb
Removing reverted package …
=> (RE-12727) Remove reverted packages from artifactory enterprise repos

lib/packaging/artifactory.rb, lib/packaging/paths.rb
This commit sets the `deb.component` property on copied debian packages when
populating a new PE repo. We set this to the PE version, which allows the
versioned subdirectories in Artifactory to be treated as separate repository
components. Without this, packages won't show up in the `dists` directory and
repo metadata won't pick them up, meaning we can't download the packages via
package manager.
=> (RE-12788) Set `deb.component` property when copying PE packages

.travis.yml, CHANGELOG.md, Gemfile, lib/packaging.rb, lib/packaging/metrics.rb, lib/packaging/util/date.rb, packaging.gemspec, tasks/jenkins.rake, tasks/ship.rake
This commit adds an `update_release_metrics` task for adding a release to the release-metrics repo (previously the release spreadsheet). This task gets called during `uber_ship_lite` in order to retain the context of what was just shipped.
=> (RE-11802) Add task for updating release-metrics

CHANGELOG.md, lib/packaging/metrics.rb
This commit turns on the `capture3` `debug` setting so that we can see command
output. In the last Puppet Platform release, puppet-agent components did not
get added for 1 out of 3 releases, so this should help us determine why.
=> (maint) Capture debug output when updating release-metrics

CHANGELOG.md, lib/packaging/sign/msi.rb
based on https://app.updates.digicert.com/e/es?s=1701211846&e=253970&elqTrackId=9f7f91354c5449a39c8dec628cf9060b&elq=38c682e663bb41df880e4dcb5755ceec&elqaid=6754&elqat=1 we replace `sha256timestamp.ws.symantec.com` with `timestamp.digicert.com`
Tested by building + signing msi package
```
echo $ret
if [[ $ret != *"Succeeded"* ]]; then exit 1; fi
sha256Servers=(http://timestamp.digicert.com/sha256/timestamp
http://timestamp.comodoca.com?td=sha256)
for timeserver in "${sha256Servers[@]}"; do
```
=> (RE-12868) Update timestamp server for windows signing

CHANGELOG.md, tasks/ship.rake
This commit reorganizes the `ship_gem_to_downloads` task to be clearer about
the cases where we do and don't want to actually attemp shipping to downloads.
Previously, the `exit` that was called to prevent the upload in the case of
unset params was preventing downstream tasks from getting run. For example,
because Bolt ships gems to rubygems, but not downloads, they have `build_gem`
set to true but no `gem_host` or `gem_path`. When shipping, none of the
`uber_ship_lite` tasks after `ship_gem_to_downloads` were getting run.
=> (RE-12869) Refactor `ship_gem_to_downloads` task

CHANGELOG.md, lib/packaging/artifactory.rb
This is a *breaking change* and will need to be coordinated with
changes to enterprise-dist.
This changes the way we handle the Artifactory 'cleanup.skip' logic.
Rather than try to calculate it at the time we upload the tarballs,
we set the 'cleanup.skip' property when we upload the 'LATEST' file.
The former approach had the problem that the version string for the tarballs
that we wanted to keep was unavailable. This approach simply uses
the string in the LATEST file as a pattern to keep.
It starts by setting 'cleanup.skip' to *false* on all the files in the target
Artifactory directory, then sets 'cleanup.skip' to *true* for all tarballs
containing the string in the LATEST file.
=> (RE-12874) Re-do the Artifactory 'cleanup.skip' logic

CHANGELOG.md, lib/packaging/platforms.rb
Needed to start packaging PDK for Fedora 31 https://github.com/puppetlabs/pdk-vanagon/pull/242
=> (PDK-1546) Add Fedora 31 to platforms

CHANGELOG.md, lib/packaging/artifactory.rb
This commit updates the `copy_final_pe_tarballs` method to include the filename
in the target path when copying to archives/releases. Previously, when trying to
copy, instead of creating a directory to copy into, it would create a single
file with the desired directory name.
=> (maint) Include filename when copying in Artifactory

CHANGELOG.md, tasks/ship.rake
This will create puppet-agent-x64.msi under windowsfips foder.
Build: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/vanagon-generic-builder/job/platform_vanagon-generic-builder_vanagon-packaging_generic-builder/631/
Output: http://builds.delivery.puppetlabs.net/puppet-agent/70994f8381ef94515592bde898a00fc579acfccb/artifacts/windowsfips/?C=M&O=A
=> (PA-3021) add windowsfips versionless symlinks

CHANGELOG.md, lib/packaging/util/version.rb, tasks/gem.rake, tasks/ship.rake
Scope of this pull-request is to add possibility build nightly gem and to create `#{gem_name}-latest-#{platform}`symlinks.
Usage: 
```
package:nightly_gem
pl:remote:link_nightly_shipped_gems_to_latest
```
Eg. result :
```
puppet-6.11.0.79.g61d0522-x86-mingw32.gem
puppet-6.11.0.79.g61d0522-x86-mingw32.gem -> puppet-6.11.0.73-x64-mingw32.gem
```
Having `-latest` version would let puppet nightly gem consumers to download the latest nightly gem with minimal effort.
I'm thinking on structuring the gems in nightlies.puppet.com like this:
```
puppet 5:
/downloads/gems/puppet5-nightly/puppet-latest.gem
/downloads/gems/puppet5-nightly/puppet-x64-mingw32.gem
etc...
puppet6: 
/downloads/gems/puppet6-nightly/puppet-latest.gem
etc...
```
=> (PA-2987) Handle puppet nightly gems

CHANGELOG.md
=> (maint) fix typo in CHANGELOG.md file that messed up the version links

CHANGELOG.md, tasks/ship.rake
Execute `pl:fetch` before  `pl:remote:link_nightly_shipped_gems_to_latest `
=> (PA-2987) fix link_nightly_shipped_gems_to_latest task

CHANGELOG.md, tasks/jenkins.rake
=> (RE-13101) Change warning to hard fail when release-metrics doesn't work.

CHANGELOG.md, lib/packaging/gem.rb, spec/lib/packaging/gem_spec.rb
We should consider platform when checking whether or not a gem has been
published.
=> (RE-13167) Make rubygem check smarter

CHANGELOG.md
=> (maint) prepare for 0.99.54 release

CHANGELOG.md
=> (maint) prepare for 0.99.55 release

lib/packaging/sign/ips.rb
New cert unpacked on rama as signing_key_2020.pem and
signing_cert_2020.pem.
=> (RE-13163) Update code signing cert for solaris signing

CHANGELOG.md, lib/packaging/artifactory.rb, lib/packaging/paths.rb
This builds on #1039 and adds logic so that the compose jobs can be set to be self-healing (if they find packages but they aren't in the correct subdir on artifactory, copy it be in the correct subdir).
Mostly, when working on https://github.com/puppetlabs/enterprise-dist/pull/3657 I was updating repos with all the missing packages and that was tedious and felt like something that was automatable. 
Need to do changelog first, but wanted to validate that we were good with this sort of change before hand
=> [RFC] Moar artifactory

CHANGELOG.md, lib/packaging/artifactory.rb, spec/lib/packaging/artifactory_spec.rb
=> (RE-9687) Set `deb.architecture` to 'all' for noarch packages shipped to artifactory

CHANGELOG.md, lib/packaging/artifactory.rb
Two parameters, `properties` and `headers` are supported by the Resource::Artifact class of
the Artifactory gem.
Add this support to our `upload_file` method, mostly for the purpose of RE-13225, which
is to allow 'cleanup.skip' to be set on uploaded artifacts.
=> (RE-13225) Allow property and header settings in Pkg::ManageArtifactory#upload_file

CHANGELOG.md, lib/packaging/platforms.rb, spec/lib/packaging/artifactory_spec.rb, spec/lib/packaging/config_spec.rb, spec/lib/packaging/deb/repo_spec.rb, spec/lib/packaging/paths_spec.rb, spec/lib/packaging/platforms_spec.rb, spec/lib/packaging/sign_spec.rb, spec/lib/packaging/util/ship_spec.rb
removed:
- cumulus-2.2-amd64
- debian-7-amd64
- debian-7-i386
- eos-4-i386
- fedora-f25-i386
- fedora-f25-x86_64
- fedora-f26-x86_64
- fedora-25-i386
- fedora-25-x86_64
- fedora-26-x86_64
- fedora-27-x86_64
- fedora-28-x86_64
- fedora-29-x86_64
- osx-10.10-x86_64
- osx-10.11-x86_64
- osx-10.12-x86_64
- osx-10.13-x86_64
- sles-11-i386
- sles-11-x86_64
- ubuntu-14.04-amd64
- ubuntu-14.04-i386
removed s390x from platforms as well
and 
clean up spec tests based on platform removals, we removed some platforms which will cause spec tests to fail, cleaned up some tests to use existing platforms.
should the changelog include all platforms we removed or just say "removed eol platforms"? ^
=> (RE-13177)(RE-13180)(RE-13183)(RE-13186) Remove old platforms + update spec

lib/packaging/platforms.rb, spec/lib/packaging/deb/repo_spec.rb, spec/lib/packaging/paths_spec.rb, spec/lib/packaging/platforms_spec.rb, spec/lib/packaging/sign_spec.rb, spec/lib/packaging/util/ship_spec.rb
we removed sles 11 and ubuntu 14.04 prematurely, add back in the platform
definitions and update spec tests where necessary.
Eventually when we do stop supporting these platforms hopefully we can simply
just revert this commit :)
no updates to changelog necessary
=> (maint) Put back sles-11 and ubuntu-14.04

lib/packaging/platforms.rb, spec/lib/packaging/config_spec.rb, spec/lib/packaging/platforms_spec.rb, spec/lib/packaging/retrieve_spec.rb, spec/lib/packaging/sign_spec.rb
update spec tests accordingly - I swapped s390x for i386 in the tests, if that's a bad idea I can change it or just remove it altogether
=> (RE-12065)(RE-12069) Remove s390x for sles and el

CHANGELOG.md, lib/packaging/artifactory.rb, spec/lib/packaging/artifactory_spec.rb
=> (RE-13386) Don't ship deb packages to a 'pool' subdirectory by default

CHANGELOG.md, lib/packaging/artifactory.rb
=> (maint) Don't use exact_match search for PE final tarballs

CHANGELOG.md, lib/packaging/platforms.rb
=> (maint) Add back osx 10.13 + update changelog

CHANGELOG.md, tasks/gem.rake, tasks/ship.rake
```
~/Workspace/puppet branch:main                                                                                             
❯ git describe
6.17.0-126-gbd1d1a786f
Successfully built RubyGem
Name: puppet
Version: 7.0.0.126.gbd1d1a7
File: puppet-7.0.0.126.gbd1d1a7-x64-mingw32.gem
```
=> (PA-3356) add puppet 7 nightly gem rake task

CHANGELOG.md, lib/packaging/artifactory.rb
=> (RE-13629) Do not use exact file match when downloading final PE tarballs

tasks/00_utils.rake
There's a lot of these in our Jenkins log files and the noise
distracting. Squelch the deprecation messages for now.
=> (maint) squelch deprecation warnings from 'ex'.

CHANGELOG.md, lib/packaging/paths.rb
=> (maint) Add the ability to determine debian component from paths containing 'main'

CHANGELOG.md, lib/packaging/gem.rb
When curl is fetching <gem>.json from rubygems, it prints download
information that is unhelpful during batch jobs. This turns that off
by adding '--silent' to the curl call.
There's also, in a seperate commit, some code formatting and output
message cleanups.
=> (maint) make curl less noisy

lib/packaging/paths.rb, lib/packaging/util/git.rb, lib/packaging/util/ship.rb, spec/lib/packaging/paths_spec.rb, spec/lib/packaging/util/ship_spec.rb
Update specs to puppet 6 pathing; prepratory work for puppet 7.
=> Add new apt pathing for puppet7

CHANGELOG.md, lib/packaging/config/params.rb
For puppet-agent 7.0.0 which is not yet released, we want packaging to use 7.0.0 as the version. Currently, it runs a `git describe` on the repo, which outputs a version similar to: `6.19.1-444`.
This commit makes `Pkg::Config.version` overridable with the `PACKAGING_PACKAGE_VERSION` environment variable.
=> (maint) Add env var to override package version

CHANGELOG.md, lib/packaging/paths.rb, spec/lib/packaging/paths_spec.rb
This is to allow us to resolved the downstream issues the change caused before re-applying
the changes.
=> (RE-13722) Mark APT pathing changes as 'FUTURE'

CHANGELOG.md, tasks/gem.rake, tasks/ship.rake
This reverts commit 86b796baee3e8a86851a822f045b8070c6cc7a25.
=> (PA-3358) Revert puppet 7 nightly gem rake task

CHANGELOG.md, lib/packaging/paths.rb, spec/lib/packaging/util/git_tag_spec.rb
Also update `git_tag` test to pull a valid ref of leatherman
=> (maint) Add puppet-tools as one of the supported apt repos

CHANGELOG.md, tasks/ship.rake
They were part of another method and not actually callable. Now part of
the `pl:` namespace.
=> (maint) create_link tasks were in the wrong place

CHANGELOG.md, lib/packaging/paths.rb
=> (maint) Include `puppet-nightly` into the apt_package_base_path

CHANGELOG.md, lib/packaging/config.rb, lib/packaging/config/params.rb, lib/packaging/config/validations.rb, tasks/config.rake, tasks/fetch.rake
Introduce a hook that allows for data validation after a pl:fetch.
Create an initial simple validation per the suggestion in RE-11821
that checks if 'project' is non-empty.
=> (RE-11821) Add config validation after pl:fetch

CHANGELOG.md, lib/packaging/platforms.rb
=> (PA-3602) Update platform hash to include Fedora 34 x86_64

CHANGELOG.md, lib/packaging/sign/dmg.rb
Primarily: fix bug that was quietly ignoring signing dmgs that weren't
in the 'apple' directory. Add 'mac' and 'osx' as considerations.
Also, do a good bit of refactoring for clarity to throw errors when
things are amiss.
The Dir.glob is still a big problem that I did not address. The signer
should be told explicitly what to sign rather than have to infer it
from the directory structure.
=> (RE-14142) Refactor dmg signing.

lib/packaging/config/params.rb, spec/lib/packaging/config_spec.rb, tasks/gem.rake
Gem::Specification recommends setting of license field. This commit adds
new parameter, `gem_license`, to allow setting of gem license attribute.
=> (PUP-11118) Add support for gem license attribute

CHANGELOG.md, lib/packaging/sign/dmg.rb
Updated the signing method for dmgs to take into
account the package archtecture when moving and
signing packages on the remote host.
=> (PE-32530) fix mac OS 11 signing

CHANGELOG.md, tasks/ship.rake
Create an analogous task to :deploy_apt_repo_to_s3, named :deploy_apt_repo_to_gcp, for syncing APT repos to GCP.
Allow for both ':deploy_apt_repo_to_gcp' to follow existing naming conventions and ':sync_apt_repo_to_gcp' which is more consistent with the rest of the code/interface.
Do some minor cleaning of the other 'deploy_<foo>_to_s3' tasks.
=> (RE-12419) Add GCP sync to 'deploy' task list

CHANGELOG.md, tasks/nightly_repos.rake, tasks/ship.rake
Confusion between nightlies.puppetlabs.com and nightlies.puppet.com caused a
breakage in s3_repo sync. Clean up and unify on 'nightlies.puppet.com'
=> (maint) make 'nightlies.puppet.com' consistent

.rubocop.yml, .travis.yml, lib/packaging/config.rb, lib/packaging/repo.rb, lib/packaging/util.rb, lib/packaging/util/apt_staging_server.rb, lib/packaging/util/build_metadata.rb, lib/packaging/util/distribution_server.rb, lib/packaging/util/ezbake.rb, lib/packaging/util/net.rb, lib/packaging/util/ship.rb, lib/packaging/util/windows.rb, packaging.gemspec, tasks/jenkins.rake, tasks/ship.rake
(RE-13941) Ship to new puppet-version based apt repos
- Broke some of the :ship tasks into smaller bits and moved them out of Rake.
- Introduced two new tasks, `pl:stage_nightly_debs` and `pl:stage_stable_debs`
for sending debs to a staging area for repos based on puppet major version.
- The above new tasks use a required set of shims from the `apt_stage_repos` gem.
- Code cleanup for my own readability and positioning for future planned development
=> (RE-13941) Add shim to support new apt shipping

CHANGELOG.md, lib/packaging/platforms.rb, spec/lib/packaging/config_spec.rb, spec/lib/packaging/deb/repo_spec.rb, spec/lib/packaging/paths_spec.rb, spec/lib/packaging/platforms_spec.rb, spec/lib/packaging/sign_spec.rb, spec/lib/packaging/util/ship_spec.rb
This removes el5, debian 8, ubuntu 18.10, osx 10.13, osx 10.14, fedora
30, and fedora 31 from the supported platform hash.
=> (RE-14105) (RE-14075) (RE-14108) (RE-14111) (RE-14114) Platform removals

CHANGELOG.md, tasks/ship.rake
Shipping '.sha1' files to Artifactory confuses it terribly. Don't ship them.
Artifactory maintains its own checksums.
=> (maint) Don't ship .sha1 files to Artifactory

CHANGELOG.md, tasks/jenkins.rake
Introduce a feature toggle, in the form of an environment variable
"NIGHTLY_SHIP_TO_GCP" that will allow nightly debs to be shipped to apt.repos.puppet.com
=> (RE-13698) Ship nightly debs to apt.repos.puppet.com

CHANGELOG.md, packaging.gemspec
~> 2.0 was very old. ~> 3.0 is much better.
=> (maint) Update artifactory gem version

CHANGELOG.md, lib/packaging/sign/ips.rb
This is a mild refactoring to possibly prep for the removal of 'sudo'
during Solaris package signing.
Mostly cleaned up long-lines and renamed a few variables to be clearer
about their purpose.
Also made provisions for ips_signing_server to contain a username much
like the other signers do.
=> (maint) tidy up solaris package signing

CHANGELOG.md, lib/packaging/config/params.rb, lib/packaging/sign/dmg.rb
=> (RE-13380) Support Apple Notarization for Puppet Packages.

CHANGELOG.md, tasks/ship.rake
This reverts commit 72721c92aee82faec95902f3c834b897b6b9f6a6.
=> Revert "(maint) begin AWS to GCP transition for apt, yum, downloads by shipping to both AWS and GCP"

CHANGELOG.md, tasks/jenkins.rake
Added support to ship nightly and stable debs to apt.repos.puppet.com. Introduced
feature toggles, via the "NIGHTLY_SHIP_TO_GCP" and "STABLE_SHIP_TO_GCP" environment variables
that will add shipping to GCP as part of the pl:jenkins:ship_nightly and pl:jenkins:ship_final
tasks
This won't switch on until the individual jobs set the environment
variable toggle.
=> (RE-13698) Add STABLE_SHIP_TO_GCP to go alongside the nightlies

CHANGELOG.md, tasks/ship.rake
Leave in place the parts that were shipping to the new debian layout,
apt.repos.puppet.com, as a later step should we decide to move that to
AWS.
=> (RE-14990) Tear down ship to GCP for apt/yum/downloads/nightlies

CHANGELOG.md, lib/packaging/platforms.rb, spec/lib/packaging/artifactory_spec.rb, spec/lib/packaging/config_spec.rb, spec/lib/packaging/deb/repo_spec.rb, spec/lib/packaging/paths_spec.rb, spec/lib/packaging/platforms_spec.rb, spec/lib/packaging/util/ship_spec.rb
Debian 9 (PA-4570), Fedora 32 (PA-4269) and 34 (PA-4278), and Ubuntu 16.04 (PA-4511) are all in the process of being deprecated from puppet-agent. This commit removes all of those platforms from lib/packaging/platforms.rb
=> (maint) Removes several deprecated platforms

CHANGELOG.md, lib/packaging/sign/rpm.rb, packaging.gemspec, spec/lib/packaging/sign_spec.rb
RPM signing works with GPG >=1 now, so stop evading it. In the old case
where /usr/bin/gpg is still gpg1, this will continue to work.
Clean up some organic code drift to isolate specific responsibility
=> (RE-15086) Clean up RPM signing
