lib/packaging/deb/repo.rb, lib/packaging/rpm/repo.rb, lib/packaging/util/execution.rb, spec/lib/packaging/deb/repo_spec.rb, spec/lib/packaging/rpm/repo_spec.rb, tasks/00_utils.rake, tasks/deb.rake, tasks/jenkins_dynamic.rake, tasks/nightly_repos.rake, tasks/pe_ship.rake, tasks/ship.rake, tasks/sign.rake
=> (RE-3702) Fix block scope bug in uber_build task.

tasks/nightly_repos.rake
This commit adds a task to tar up a repo for shipping as part of repo
deployment. This task assumes that prepare_signed_repos has been run
previously for the build.
=> (RE-4842) Add archival task to nightly_repos.rake

tasks/ship.rake
This commit updates the automation to allow shipping of dmgs for vanagon projects ( vanagon_project set to true ) and when build_dmg is not set. It also updates the source directory for the rsync to be pkg/apple/ instead of pkg/apple/*.dmg.  This adds support for apple projects that have a repo defined, such as PC1.
=> (RE-2542) shipping staging automation for osx

lib/packaging/osx.rb
Prior to this commit, the variables used in this file were being loaded
prematurely. As soon as rake was invoked, they would be populated.
However, the correct value was not guarenteed to be there initially. If
we load data from the build-data repo, for instance, it is not
available, because the file is not reloaded and the variables are not
reassigned. This commit ensures that if we load data at a later point in
the process, we will correctly populate these variables.
=> (maint) Do not load variables prematurely

tasks/tickets.rake
Previously, the `tickets` task generated two subtasks for reconciling
jira tickets and git commits.
This commit consolidates the subtasks into one, and updates the
description to use the ticketmatch script that Thomas wrote.
Also updated example usage to use Nick's jira account.
=> (maint) Update ticketmatch reconciliation step

lib/packaging/config/platforms.rb, lib/packaging/util/platform.rb, spec/lib/packaging/util/platform_spec.rb
This PR includes some platforms (fedora) that were neglected in the initial PR as well as some improved error messaging, and more/better tests.
=> (RE-5524) Fixes and more tests for Platform module

tasks/tickets.rake
previously this was hardcoded to eric sorenson
=> (maint) use owner var in ticket creation

lib/packaging/config.rb, lib/packaging/config/params.rb, lib/packaging/deb/repo.rb, tasks/fetch.rake, tasks/ship.rake
Reverts puppetlabs/packaging#451
=> Revert "(RE-1198) Change how/where deb packages are signed and deployed"

lib/packaging/config.rb, lib/packaging/config/params.rb, lib/packaging/deb/repo.rb, tasks/fetch.rake, tasks/ship.rake
Always be reverting
Reverts puppetlabs/packaging#466
=> Revert "Revert "(RE-1198) Change how/where deb packages are signed and deployed""

lib/packaging.rb, lib/packaging/config/params.rb, lib/packaging/nuget.rb, tasks/ship.rake
Add new target to packaging scripts to support nuget (nupkg) style
packages for windows.
Note - this supersedes #471
=> (RE-5681) Ship Nuget Packages to Repo

tasks/agent-tickets.rake
This task should include updating genconfig2 and beaker-hostgenerator.
=> (RE-6130) Update the description of the genconfig task

tasks/ship.rake
A few things have come up that aren't quite working correctly. We should fix these!
=> (WIP) (maint) Reduce the quirks of shipping

tasks/ship.rake
Currently shipping is weird and a bit quirky. Let's try to make it a little better!
=> (maint) DMGs don't get shipped to production

lib/packaging.rb, lib/packaging/deb.rb, lib/packaging/gem.rb, lib/packaging/ips.rb, lib/packaging/osx.rb, lib/packaging/util.rb, lib/packaging/util/git.rb, lib/packaging/util/net.rb, spec/lib/packaging/util/git_spec.rb, tasks/00_utils.rake, tasks/build.rake, tasks/deb.rake, tasks/jenkins.rake, tasks/jenkins_dynamic.rake, tasks/mock.rake, tasks/nightly_repos.rake, tasks/pe_ship.rake, tasks/retrieve.rake, tasks/rpm.rake, tasks/ship.rake, tasks/sign.rake, tasks/tag.rake, tasks/version.rake, templates/downstream.xml.erb
SAY YOU'LL DEPRECATE MY TASKS AGAIN
=> (maint) UNRAKE MY HEARTTTTTTTT

lib/packaging/ips.rb
troubleshoot suspected word splitting.
=> (maint) fix potential packaging issue

tasks/nightly_repos.rake
When shipping nightlies that use a whitelist (such as puppet-agent) the shipped artifacts were unique directories.  This was different than how non-whitelisted projects are shipped (such as puppetdb).  This update ensures that the shipped -latest has a symlink to the appropriate latest set.
```
[root@ilhoe2uxhhro2t1 puppet-agent-latest]# ls -la
total 0
drwxr-xr-x 3 root root  39 Apr 11 20:14 .
drwxr-xr-x 6 root root 108 Apr 11 21:04 ..
drwxr-xr-x 4 root root  28 Apr 11 18:55 repo_configs
lrwxrwxrwx 1 root root  62 Apr 11 20:14 repos -> ../puppet-agent/740f20af50043ff31bde943f0d273f4cd40e4acb/repos
```
Tested puppet-agent only ships the whitelisted FOSS platforms and that puppetdb ships all.
```
21:50 $ diff -rq pkg/puppet-agent-latest/repos tmp/pkg/puppet-agent-latest/repos
Only in …
```
=> (RE-7003) Ship nightlies with symlink to latest repos

tasks/puppet-agent-release-tickets.rake
Tested at https://jira1-test.ops.puppetlabs.net/browse/PA-338
=> (maint) Remove the superflous RE ticket

lib/packaging/util/jenkins.rb
Now syncing stdout so we get polling messages as and when they happen
=> (QE-3891) PuppetDB packaging job is timing out

tasks/nightly_repos.rake
There was an issue when running the nightly_repos.rake file. A circular symlink was created and directories would be recursively made indefinitely. This fix takes out one of the calls to create a symlink (because it was called twice and should not have been) which fixes the issue. The symlink is set properly and the correct directories are made in the correct locations.
=> (RE-6147) Fix recursive links in internal puppet-agent ship

tasks/pe_ship.rake
We had the wrong variable name for incoming in the transfer from
enterprise-dist. Also we want to sign these repos with the pluto key.
=> (maint) Fix the aptly test

tasks/pe_ship.rake
Reverts puppetlabs/packaging#579
=> Revert "(RE-7445) Migrate pe repos to use aptly"

tasks/pe_ship.rake
Reverts puppetlabs/packaging#580
=> Revert "Revert "(RE-7445) Migrate pe repos to use aptly""

tasks/ship.rake
This is functionality to add the project-arch.msi symlinks that have no
version. The code itself looks for the symlink (if it's there already) and if
the source package exists before symlinking.
This should not break any legacy builds of puppet-agent as the lookup for the
existing file will prevent overwriting anything
=> (PA-467) Add windows versionless symlinks to ship jobs

tasks/ship.rake
So, there's a lot of history here. We set packages to be immutable as
part of the shipping so they don't get overwritten, which doesn't play
well with symlinks. So we need to use FileUtils.ln(). Also,
File.symlink() and FileUtils.ln() behave differently with respect to
whether or not they expect the path for the source to be relative to pwd
or relative to the link target. By using hard links we should be able to
set them to be immutable without breaking everything.
=> (PA-467) More linking work

lib/packaging/osx.rb, lib/packaging/util/net.rb, spec/lib/packaging/util/net_spec.rb
Reverts puppetlabs/packaging#595
=> Revert "(PA-552) OSX signing should not echo the command output"

lib/packaging/gem.rb, lib/packaging/util/execution.rb, lib/packaging/util/net.rb, lib/packaging/util/serialization.rb, spec/lib/packaging/util/execution_spec.rb, tasks/apple.rake, tasks/deb.rake, tasks/retrieve.rake
Reverts puppetlabs/packaging#604
=> Revert "(RE-8186) improved error handling"

lib/packaging/util/net.rb, spec/lib/packaging/util/net_spec.rb
Reverts puppetlabs/packaging#618
=> Revert "Revert "(RE-8187) fail more!""

tasks/pe_ship.rake
This adds a loop to make sure aptly isn't running before we try to lock
the database.  LevelDB doesn't remove/re-add its lockfile each time it
takes/releases the lock, rather it seems to be doing some filesystem
locking.
=> (maint) Make sure aptly isn't running before we try to update

tasks/pe_ship.rake
Currently we create rpm repo metadata for pez/feature repos
on every promotion. Since nothing uses the pez repos as actual
repos, we don't need to create that metadata.
=> (maint) Skip creating unused metadata in pez repos

lib/packaging/repo.rb, spec/lib/packaging/repo_spec.rb
This reverts commit 1ed428ffe04efcdf728cd860486237702ea2a6b6.
=> Revert "(RE-8615) Skip platforms without repos when creating repo archives"

lib/packaging/config.rb, tasks/ship.rake
This reverts commit 1e841379f4ca78a70a5258ac9ea957501b223767.
=> Revert "(RE-8707) Add `platform_data` to <ref>.yaml"

lib/packaging/platforms.rb
Reverts puppetlabs/packaging#685
=> Revert "(CPR-407) Enable shipping fedora packages to repos not prepended with f"

tasks/ship.rake
I'm not blocking the burji3 switch on this, but it seems like a good cleanup to have.
=> add --delete to rsync

lib/packaging/config.rb
This commit updates platform_data to make use of tag_from_artifact_path when mapping platform tags to artifact paths for consumption by beaker. Previously, we were relying on artifacts_path for the mapping, which makes assumptions about what we expect to find on builds. Now we take the actual, existing artifact paths and map to tags.
=> (maint) Refactor platform_data collection

tasks/retrieve.rake
This commit refactors the retrieve task to only look for the <ref>.yaml file when using FOSS_ONLY to ship. Previously, this caused problems during internal ships because we were looking for <ref>.yaml in directories other than the 'artifacts' directory.
=> (maint) Only retrieve <ref>.yaml when using FOSS_ONLY

tasks/retrieve.rake
This commit moves the `package_url` variable to higher up in the fetch process it is needed by both foss_only and regular retrieval. I've also begun some cleanup of this file.
=> (maint) Mistakes and cleanup

lib/packaging.rb, lib/packaging/retrieve.rb, spec/lib/packaging/retrieve_spec.rb, tasks/retrieve.rake
see commit messages for more details
=> (maint) Refactor `retrieve`

CHANGELOG.md, lib/packaging/config/params.rb
Conflicts were resolved by favoring the 1.0.x branch.
=> Merge master -> 1.0.x

lib/packaging/paths.rb
In an effort to maintain functionality of current nightlies pipelines, a
`legacy` option was added to Pkg::Paths.repo_path(). However, this did
not maintain behavior from packaging#master
Pkg::Util::Platform.repo_path(), which is causing existing nightly
pipelines to only ship repo configs, not actual repos/packages.
=> (RE-9889) `legacy` wasn't maintaining legacy behavior

lib/packaging/platforms.rb
Add macOS 10.13 to PLATFORM_INFO hash
=> (PA-1492) Add macOS 10.13 (High Sierra)

tasks/ship.rake
This was another typo / copy-pasta mistake. I'm sorry. :(
=> (maint) Update apt repos on signing server, not staging server

lib/packaging/retrieve.rb, spec/lib/packaging/retrieve_spec.rb, tasks/nightly_repos.rake, tasks/retrieve.rake
This PR refactors the retrieve function and tasks to have fewer, more sensible parameters, and adds better failure messaging. See individual commit messages for details.
=> (maint) Refactor retrieve and some other stuff

CHANGELOG.md
whoops i put the 1.0.x stuff in the master branch changelog
=> (maint) release prep for 1.0.x branch

Gemfile, lib/packaging.rb, lib/packaging/config.rb, lib/packaging/metadata.rb, packaging.gemspec, spec/lib/packaging/config_spec.rb, spec/lib/packaging/metadata_spec.rb, spec/spec_helper.rb
See individual commit messages for details.
=> (RE-11090) Use metadata: Take 2

Gemfile, packaging.gemspec, spec/spec_helper.rb
See individual commit messages for details.
=> (maint) Dependency clean-up

CHANGELOG.md, lib/packaging/sign/rpm.rb
=> (maint) Don't check if AIX packages have signatures

README.md, lib/packaging/util/net.rb, tasks/00_utils.rake, tasks/jenkins.rake, tasks/nightly_repos.rake, tasks/sign.rake, templates/packaging.xml.erb
See individual commit messages for details.
=> (RE-11584) Stop calling bootstrap within packaging itself

lib/packaging/util/net.rb, lib/packaging/util/ship.rb, spec/lib/packaging/util/ship_spec.rb
see individual commit messages for details
=> (RE-11741) Rogue puppet-latest links

lib/packaging/sign/msi.rb
This pr solves latency issues of timeservers by:
* adding multiple time servers
* adding a retry mechanism of 5 tries per server.
=> (RE-12205) Add retry + other time servers to msi signing

lib/packaging/paths.rb, lib/packaging/util/ship.rb, spec/lib/packaging/paths_spec.rb, tasks/jenkins.rake
see individual commit messages for details
=> (RE-10207) Automate updating release package symlinks

lib/packaging/artifactory.rb
We need this ability to be able to use the enterprise repos we're
promoting into.
=> (maint) Add ability to promote debian packages into a component

lib/packaging/deb/repo.rb, spec/lib/packaging/deb/repo_spec.rb
In an attempt into understanding the SIGTERM issues we've been
occasionally spotting in packaging, I noticed that rspec didn't run on
my machine. Turns out I had 'keychain' installed and the spec tests
didn't allow for that. rspec was failing on my box.
Update the spec test to allow for this possibility.
Also sneak in a minor bit of code refactoring in Pkg::Deb::Repo.sign_repos
=> (maint) Make the Pkg::Deb::Repo #sign_repos spec allow for the 'keychain' command.

lib/packaging/artifactory.rb
`download_packages` downloads specified packages based on md5sum
`ship_pe_tarballs` grabs tarballs from specified directory and ships them to specified artifactory repo + paths
Relates to: https://github.com/puppetlabs/enterprise-dist/pull/3536
=> (RE-12499) Add artifactory tasks to download and ship PE packages

CHANGELOG.md
Is this more of a "changed" or a "fixed"? because it changes the functionality but it fixes it to what we'd expect
=> (maint) Prepare for 0.99.41 release

lib/packaging/artifactory.rb
we do this on saturn so do it on artifactory
=> (RE-12728) Update LATEST file on artifactory

lib/packaging/artifactory.rb
Part 1: Create a method to clear all 'cleanup.skip' properties on
artifacts within a directory. Call it in ship_pe_tarballs before we start
uploading tarballs to that directory.
Part 2: Set 'cleanup.skip' property on any uploaded pe tarball
'unset_cleanup_skip_on_artifacts' is called on an Artifactory
directory from ship_pe_tarballs just before uploading artifacts to
Artifactory. Then as the new artifacts are uploaded, 'cleanup.skip' is
set to 'true' on each one, maintaining the property on the latest artifact
only
Some implementation notes:
I turned the logic in 'ship_pe_tarballs' inside out to facilitate this.
In unset_cleanup_skip_on_artifacts, the call to
Artifactory::Resource::Artifact.property_search followed by a directory
filter seems inefficient to me but resulted in the most …
=> (RE-12731) Implement Artifactory cleanup policy

lib/packaging/artifactory.rb
and also add method to copy tarballs to archives/releases
pairs with https://github.com/puppetlabs/enterprise-dist/pull/3553
=> (RE-12734) Add functionality for downloading final pe tarballs

lib/packaging/artifactory.rb
To prep for the above I also did a little bit of refactoring so that
intentions were made a bit more clear.
=> (maint) Add origin path to message during package promotion.

lib/packaging/config.rb, lib/packaging/paths.rb, lib/packaging/platforms.rb, lib/packaging/sign/msi.rb, spec/lib/packaging/artifactory_spec.rb, spec/lib/packaging/config_spec.rb, spec/lib/packaging/platforms_spec.rb, spec/lib/packaging/util/ship_spec.rb
=> (PA-2839) add support for windowsfips

.github/pull_request_template.md
to remind users to update changelog with any notable changes
words are hard, does this message seem alright?
=> (RE-12861) Add pull request template

CHANGELOG.md
=> (maint) Update changelog for 0.99.46 release

CHANGELOG.md
=> (maint) update changelog for 0.99.47 release

CHANGELOG.md, lib/packaging/artifactory.rb, lib/packaging/paths.rb
=> (maint) Set debian component properly when populating repos

CHANGELOG.md
=> (RE-12849) Prep changelog for 0.99.48 release

CHANGELOG.md, lib/packaging/artifactory.rb
=> (maint) Fix parameter name

CHANGELOG.md, lib/packaging/artifactory.rb
=> (maint) Include target directory in output

CHANGELOG.md
=> (maint) Prep for 0.99.49 release

.github/workflows/ruby.yml, CHANGELOG.md
=> (RE-12928) Release packaging 0.99.50

CHANGELOG.md
=> (maint) prepare for 0.99.52 release

lib/packaging/sign/msi.rb
If the same msi package is found in windows and windowsfips
folders it will be overwritten while rsync them to signing server
With this change, the directory structure where msi files are
found is replicated to signing server
=> (maint) fix msi signing

CHANGELOG.md, lib/packaging/sign/msi.rb
=> (RE-13191) Use new directory throughout the msi signing

CHANGELOG.md, lib/packaging/config.rb
Took the opportunity to do some minimal cleaning in platform_data as well.
=> (RE-13220) Remove noisy message from Pkg::Config.platform_data method

CHANGELOG.md
=> (maint) Prep for 0.99.56 release

CHANGELOG.md, lib/packaging/artifactory.rb
=> (maint) Add `search_with_path` artifactory method

CHANGELOG.md
=> (maint) Prep for 0.99.58 release

CHANGELOG.md, lib/packaging/artifactory.rb
=> (maint) Update `download_packages` to optionally add a search path

CHANGELOG.md
=> (maint) Prepare for 0.99.59 release

CHANGELOG.md, lib/packaging/platforms.rb, spec/lib/packaging/platforms_spec.rb
=> (PA-3129) add Ubuntu 20.04

CHANGELOG.md
=> (maint) Prepare for 0.99.60 release

CHANGELOG.md, lib/packaging/platforms.rb, spec/lib/packaging/artifactory_spec.rb, spec/lib/packaging/config_spec.rb, spec/lib/packaging/paths_spec.rb, spec/lib/packaging/platforms_spec.rb, spec/lib/packaging/sign_spec.rb, spec/lib/packaging/util/ship_spec.rb
=> Undo removals

CHANGELOG.md, lib/packaging/paths.rb, spec/lib/packaging/paths_spec.rb
From appearances it seems that a simple deletion of conditionals are
all that is needed to do this?
=> (RE-13273) Remove obsolete handling of PC1 repos

lib/packaging/paths.rb
After RE-13273 I noticed that this could use some cleanup of invariant code inside the cases and loops.
This seems more readable to me. Curious if everyone else does.
=> Hack: refactor from case/loop invariant code

CHANGELOG.md
=> prep for 0.99.62 release

CHANGELOG.md, lib/packaging/artifactory/extensions.rb
=> Fix issue affecting artifactory pattern searches

CHANGELOG.md
=> (maint) update changelog

CHANGELOG.md, lib/packaging/paths.rb, lib/packaging/util/ship.rb, spec/lib/packaging/paths_spec.rb, tasks/ship.rake
=> (RE-13303) Update rolling repo link creation

CHANGELOG.md
=> prep for 0.99.66 release

CHANGELOG.md, lib/packaging/platforms.rb
=> (PA-3212) add Fedora 32

CHANGELOG.md
=> changelog updates for 0.99.67

CHANGELOG.md
=> Changelog for 0.99.68

CHANGELOG.md, lib/packaging/platforms.rb
=> (PA-3386) Add redhat8-aarch64

CHANGELOG.md
=> (maint) 0.99.69 prep

CHANGELOG.md, lib/packaging/paths.rb
=> (maint) Fix bug in component regex

CHANGELOG.md
=> (maint) Prepare for 0.99.72 release

CHANGELOG.md
=> (maint) prep for 0.99.73 release

CHANGELOG.md, lib/packaging/util/net.rb
=> (maint) Update bundle install to use ruby 2.5.1

CHANGELOG.md, lib/packaging/paths.rb, lib/packaging/platforms.rb, spec/lib/packaging/paths_spec.rb
=> (PA-3478) add Ubuntu 2004 aarch64 to platform hash

CHANGELOG.md
=> Preparing for release.

README.md
=> (RE-13415) Update packaging README with new GPG key

CHANGELOG.md, lib/packaging/sign/msi.rb
updated sha1 signing servers since the existing ones started failing
=> (maint) update sha1 signing servers

CHANGELOG.md
=> Prep for 0.99.76 release

CHANGELOG.md, lib/packaging/platforms.rb
=> (RE-11477) Remove platforms that EOL'd with platform6

.github/workflows/ruby.yml, CHANGELOG.md, lib/packaging/platforms.rb, spec/lib/packaging/artifactory_spec.rb, spec/lib/packaging/config_spec.rb, spec/lib/packaging/paths_spec.rb, spec/lib/packaging/platforms_spec.rb, spec/lib/packaging/retrieve_spec.rb, spec/lib/packaging/sign_spec.rb
=> (PA-3614) Update platform hash with macOS 11 Big Sur

CHANGELOG.md
=> (main) Preparing for 0.99.77 release.

CHANGELOG.md
=> (maint) 0.99.78 release prep

CHANGELOG.md, lib/packaging/artifactory.rb, tasks/ship.rake
=> (maint) don't upload checksums to artifactory before uploading artifacts

CHANGELOG.md
=> (maint) Prep 0.99.80 release

CHANGELOG.md, lib/packaging/artifactory.rb
Add some informational clarity and tidy up the code a bit for #download_packages
=> (maint) Refactor artifactory download_packages

.rubocop.yml, .travis.yml, CHANGELOG.md, lib/packaging/config.rb, lib/packaging/repo.rb, lib/packaging/util.rb, lib/packaging/util/apt_staging_server.rb, lib/packaging/util/build_metadata.rb, lib/packaging/util/distribution_server.rb, lib/packaging/util/ezbake.rb, lib/packaging/util/net.rb, lib/packaging/util/ship.rb, lib/packaging/util/windows.rb, packaging.gemspec, tasks/jenkins.rake, tasks/ship.rake
Revert "Revert "(RE-13941) Take yet another swing at new apt repo shipping""
This reverts commit 5c6f8d805a80a50976ce985917ef4516554eb38f.
=> (RE-13941) New apt repo ship, try #3

CHANGELOG.md
=> (maint) prep for 0.105.0 release

CHANGELOG.md
=> (maint) Update changelog for 0.106.0-release

lib/packaging/sign/dmg.rb
=> (maint) Set size when creating image.

CHANGELOG.md, lib/packaging/config/params.rb, lib/packaging/sign/dmg.rb
Reverts puppetlabs/packaging#1136
=> Revert "(RE-13380) Support Apple Notarization for Puppet Packages."

lib/packaging/sign/dmg.rb
Reverts puppetlabs/packaging#1141
=> Revert "(maint) Set size when creating image."

CHANGELOG.md, lib/packaging/sign/ips.rb
=> (maint) solaris signing updates

CHANGELOG.md, lib/packaging/artifactory.rb
=> (maint) add nil handling

README.md, spec/lib/packaging/util/git_spec.rb, spec/lib/packaging/util/git_tag_spec.rb
=> (maint) Update git urls in spec tests

CHANGELOG.md
=> (maint) prepare for 0.160.1 release

CHANGELOG.md
=> (maint) Update changelog for 0.106.2 release.

CHANGELOG.md, lib/packaging/platforms.rb, spec/lib/packaging/paths_spec.rb, spec/lib/packaging/platforms_spec.rb
=> (PA-4235) Add Ubuntu 22.04

CHANGELOG.md
=> (maint) Prep for 0.107.0 release

CHANGELOG.md, lib/packaging/platforms.rb
=> (PA-4444_ Adds Fedora 36 to platforms

CHANGELOG.md, lib/packaging/sign/rpm.rb
=> (maint) Added support for signing RPMs using gpg >= 2.1

CHANGELOG.md
=> (maint) Update changelog for 0.107.1 release.

CHANGELOG.md, lib/packaging/config/params.rb, lib/packaging/sign/msi.rb
=> (maint) Move GCP bucket names for MSI signing to params.

CHANGELOG.md
=> (maint) Update changelog for 0.107.2 release.

CHANGELOG.md
=> (maint) prep for 0.108.0 release

CHANGELOG.md, lib/packaging/rpm/repo.rb, spec/lib/packaging/rpm/repo_spec.rb
Also clean up spec tests around repo_ship
=> Fix ship_repo_configs when nothing to ship
